<a href="https://colab.research.google.com/github/Hongbi-Kim/Writing_lyrics/blob/master/220428_html_fastapi_ngrok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

코랩이 구글 드라이브에 마운트돼 있어야 합니다.

구글드라이브에 front-end 숏컷이 만들어져 있어야 합니다.

결과 표시를 위해서 txt파일로 저장하는 명령을 추가했습니다.

In [2]:
!pip install transformers

     |████████████████████████████████| 4.0 MB 14.7 MB/s 
     |████████████████████████████████| 596 kB 76.4 MB/s 
     |████████████████████████████████| 6.6 MB 58.6 MB/s 
     |████████████████████████████████| 895 kB 92.9 MB/s 
     |████████████████████████████████| 77 kB 7.7 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
!pip install konlpy
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git 
%cd Mecab-ko-for-Google-Colab/
!bash install_mecab-ko_on_colab190912.sh
%cd ../

     |████████████████████████████████| 19.4 MB 15.0 MB/s 
     |████████████████████████████████| 448 kB 66.9 MB/s 
Cloning into 'Mecab-ko-for-Google-Colab'...
remote: Enumerating objects: 115, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 115 (delta 11), reused 10 (delta 3), pack-reused 91
Receiving objects: 100% (115/115), 1.27 MiB | 30.25 MiB/s, done.
Resolving deltas: 100% (50/50), done.
/content/Mecab-ko-for-Google-Colab
Installing konlpy.....
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2022-05-01 03:27:47--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22c5:2ef4, 2406:da00:ff00::3403:4be7, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
L

In [4]:
from collections import Counter

In [5]:
# 구글 드라이브에서 모델, 토크나이저 불러오기
import os
import time
import datetime
from google.colab import drive

import pandas as pd
import seaborn as sns
import numpy as np
import random
import re

import torch
from torch.utils.data import Dataset, DataLoader, random_split, RandomSampler, SequentialSampler
torch.manual_seed(42)


from transformers import GPT2LMHeadModel,  GPT2Tokenizer, GPT2Config, GPT2LMHeadModel
from transformers import AdamW, get_linear_schedule_with_warmup

# gpt3-kor-small_based_on_gpt2
from transformers import BertTokenizerFast, GPT2LMHeadModel
model = GPT2LMHeadModel.from_pretrained('/content/drive/MyDrive/gpt3_topic')
tokenizer_gpt3 = BertTokenizerFast.from_pretrained('/content/drive/MyDrive/gpt3_topic')
input_ids = tokenizer_gpt3.encode("text to tokenize")[1:]  # remove cls token

In [ ]:
#from konlpy.tag import Okt
#okt = Okt()

In [6]:
from konlpy.tag import Mecab
mecab = Mecab()

In [7]:
device = torch.device("cuda")
model.cuda()

seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)
model = model.to(device)

In [8]:
model.eval()
def lyric_generator(gen, lyric):
  prompt = f"<|startoftext|> <{gen}> {lyric}"
  generated = torch.tensor(tokenizer_gpt3.encode(prompt)[1:]).unsqueeze(0)
  generated = generated.to(device)

  print(generated)

  sample_outputs = model.generate(
                                  generated, 
                                  #bos_token_id=random.randint(1,30000),
                                  do_sample=True,   
                                  top_k=50, 
                                  max_length = 350,
                                  #max_length = len(lyric) + 350,
                                  top_p=0.95, 
                                  num_return_sequences=1,
                                  repetition_penalty=1.1
                                  )
  for i, sample_output in enumerate(sample_outputs):
    # result = "{}: {}".format(i, tokenizer_gpt3.decode(sample_output, skip_special_tokens=True))
    result = tokenizer_gpt3.decode(sample_output, skip_special_tokens=True)
    result = re.sub(r"<br>", '\n', result)
    lyrictxt = open(r'/content/drive/MyDrive/front-end/lyrictxt.txt','w')
    myString = result
    lyrictxt.write(myString)
    lyrictxt.close()
    # re.sub(r'[a-z]','',result.split('\n')[-1])
    # result = re.sub(r'[a-z]','',result.split('\n')[-1])   
    # result = result[len(lyric)+1:]
    # print(re.sub(r'[a-z]','',result))
    print(result)
  return result
  # for i, sample_output in enumerate(sample_outputs):
  #   # result = "{}: {}".format(i, tokenizer_gpt3.decode(sample_output, skip_special_tokens=True))
  #   result = tokenizer_gpt3.decode(sample_output, skip_special_tokens=True)
  #   result = re.sub(r"<br>", '\n', result)
  #   # re.sub(r'[a-z]','',result.split('\n')[-1])
  #   # result = re.sub(r'[a-z]','',result.split('\n')[-1])   
  #   # result = result[len(lyric)+1:]
  #   # print(re.sub(r'[a-z]','',result))
  #   print(result)
  # return result

In [9]:
def decide_topic(gen, lyric):

  d_topic1 = ['밤','심장','순간','날','눈','몸','숨','눈빛','머리','시선','맘','끝','손','기분','춤','시작','입술','원','준비','소리',
              '음악','느낌','때','완벽','안','위','필요','리듬','입','전']
  d_topic2 = ['눈','밤','속','순간','꿈','손','하늘','날','위','끝','숨','세상','맘','심장','시간','빛','바람','눈빛','안','기분','소리',
              '시작','별','길','때','몸','곳','노래','향기','시선']
  d_topic3 = ['남자','집','여자','매력','친구','옷','머리','생일','기분','전화','축하','노래','화장','밥','티','커피','눈치','정신','아침',
              '스타일','오늘','애','문자','몸매','분위기','얼굴','영화','오빠','번호','생일날']
  d_topic4 = ['엄마','돈','아빠','인생','나이','공부','아저씨','집','왕','애','학교','금','배','물','개','아이','맛','키','형','밥','산타',
              '오빠','몫','랩','산','동생','부모','술','라면','남']
  d_topic5 = ['춤','몸','음악','머리','인생','볼륨','준비','리듬','소리','다리','무대','돈','잔','비트','걱정','남','승리','젋음','발','폼',
              '모두','허리','땀','함성','해변','엉덩이','차','피해','게임','해결']

  b_topic1 = ['꿈','속','하늘','빛','위','끝','세상','순간','길','별','손','어둠','숨','곳','시간','시작','바람','안','눈','밤','미래','태양',
              '현실','구름','아래','날','달','내일','달빛','삶']
  b_topic2 = ['사랑','말','날','마음','생각','맘','사람','시간','모습','속','때','가슴','행복','곁','눈물','기억','세상','하루','이상','일','눈',
              '오늘','앞','끝','여자','필요','추억','친구','혼자','밤']
  b_topic3 = ['돈','집','엄마','친구','인생','나이','밥','아빠','술','오빠','차','키','남','여자','부모','잔','학교','동네','아저씨','크리스마스',
              '라면','한잔','결혼','공부','우정','애','모두','언니','배','누나']
  b_topic4 = ['춤','음악','바다','리듬','위','파도','여름','노래','몸','소리','밤','아래','태양','바람','하늘','조명','도시','볼륨','햇살','분위기',
              '기분','여행','모래','파티','걱정','일상','불빛','무대','산','해']
  b_topic5 = ['눈','맘','날','눈빛','밤','기분','심장','머리','손','순간','말','입술','시선','향기','몸','느낌','입','때','원','숨','상상','남자',
              '눈치','매력','준비','완벽','오늘','전','미소','표정']

  token = mecab.pos(lyric)
  #token = okt.pos(lyric)
  #print(token)

  word_list = []
  for t in token:
    if t[1] == 'NNG':
    #if t[1] == 'Noun':
      word_list.append(t[0])
  #print(word_list)
  
  topic_counts = []
  # Counter().moset_common(n)의 경우 같은 수의 카운트는 발생한 순으로 반환
  # 댄스 1-2-3-4-5
  if gen == '댄스':
    for word in word_list:
      if word in d_topic1:
        topic_counts.append('topic1')
      if word in d_topic2:
        topic_counts.append('topic2')
      if word in d_topic3:
        topic_counts.append('topic3')
      if word in d_topic4:
        topic_counts.append('topic4')
      if word in d_topic5:
        topic_counts.append('topic5')

  # 발라드 1-2-3-5-4
  elif gen == '발라드':
    for word in word_list:
      if word in b_topic1:
        topic_counts.append('topic1')
      if word in b_topic2:
        topic_counts.append('topic2')
      if word in b_topic3:
        topic_counts.append('topic3')
      if word in b_topic5:
        topic_counts.append('topic5')
      if word in b_topic4:
        topic_counts.append('topic4')  

  if topic_counts == []:
    topic = 'topic6'
  else:
    topic = Counter(topic_counts).most_common(1)[0][0]
  
  print(topic_counts)
  print(Counter(topic_counts).most_common())
  gen = gen + topic  

  return gen, lyric

In [10]:
decide_topic('발라드', '사랑 하늘')

['topic2', 'topic1', 'topic4']
[('topic2', 1), ('topic1', 1), ('topic4', 1)]


('발라드topic2', '사랑 하늘')

In [11]:
def decide_regen(input):
  val = []
  # for i in input.split('<br>'):
  for i in input.split('\n'):
    val.append(str(bool(re.search(r'[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]',i))))

  eng = []
  space = []
  for char in input:
    if re.sub(r'[a-z]','',char) == "":
      eng += char
    elif char == " ":
      space += char
  eng_ratio = len(eng)/(len(input)-len(space))

  if (len(set(val[1:])) == 1) & ('False' in set(val[1:])) == True:
    print((len(set(val[1:])) == 1) & ('False' in set(val[1:])))
    print(input)
    output = 'regenerate'
  elif eng_ratio > 0.2:
    print(eng_ratio)
    print(input)
    output = 'regenerate'
  else:
    print(eng_ratio)
    output = 'pass'
  
  return output

In [12]:
def remove_lastEng(a):
  # 마지막 줄에 영어만 있다면
  if re.sub(r'[a-z\n]','',a.split('\n')[-1]).strip() == "" :
    b = a.split('\n')[:-1]
    c = ""
    for i in b:
      if i == ' ':
        i = re.sub(r" ", "\n \n", i)
      c += i
      c = re.sub(r"  ", "\n", c)
      output = c
  else:
    output = a
  return output

In [13]:
def ai_lyrics(gen, lyric):
  #print(decide_topic(gen,lyric)[0])
  result = lyric_generator(decide_topic(gen,lyric)[0],decide_topic(gen,lyric)[1])

  for _ in range(10):
    if len(result) < 350:
      print('길이 재생성이 필요합니다')
      result = lyric_generator(decide_topic(gen,lyric)[0],decide_topic(gen,lyric)[1])
    else:
      break

  if decide_regen(result) == 'regenerate':
    print('한글 재생성이 필요합니다.')
    #print(gen)
    output = ai_lyrics(gen, lyric)
  else:
    output = remove_lastEng(result)

  print(output)
  return

In [14]:
!pip install fastapi nest-asyncio pyngrok uvicorn aiofiles python-multipart # 패스트API 설치

# 패스트API 관련 모듈 불러오기
from fastapi import FastAPI, Request, Form
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
import nest_asyncio
from pyngrok import ngrok

import uvicorn

# 사용할 디렉토리 만들기
!mkdir templates
!mkdir static

     |████████████████████████████████| 54 kB 3.1 MB/s 
     |████████████████████████████████| 745 kB 27.9 MB/s 
     |████████████████████████████████| 53 kB 2.3 MB/s 
     |████████████████████████████████| 58 kB 7.3 MB/s 
     |████████████████████████████████| 10.9 MB 91.8 MB/s 
     |████████████████████████████████| 79 kB 10.9 MB/s 
     |████████████████████████████████| 58 kB 7.8 MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.1.0-py3-none-any.whl size=19007 sha256=4bb489cb66f4287774098e4fd9890bd66131b4169f100c7e0123cc7bcc7f384b
  Stored in directory: /root/.cache/pip/wheels/bf/e6/af/ccf6598ecefecd44104069371795cb9b3afbcd16987f6ccfb3
  Created wheel for python-multipart: filename=python_multipart-0.0.5-py3-none-any.whl size=31678 sha256=6fdc9fe887c8b80fe5588b6cda082bb01334274860c24eecbdf6c4de8589b41d
  Stored in directory: /root/.cache/pip/wheels/2c/41/7c/bfd1c180534ffdcc0972f78c5758f89881602175d48a8bcd2c
Successfully built pyngrok python-multipart


In [ ]:
#  <input class="lead mb-5" type="text" id="lyric" name="lyric" value=" 예) 여긴  동화  속  세상  네버랜드 ">

In [15]:
%%writefile templates/input.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>너의 이야기를 들려줘</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="./assets/로고.png" />
        <link href="{{ url_for('static', path='/styles.css') }}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body id="page-top">
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                <h1>AI 작사가 에이나</h1>
                <h3 class="mb-5"><em> </em></h3>
          <form action="/topic" method="post">
            <h4><strong><label for="gen">발라드와 댄스 중 한 가지 장르를 입력해 주세요</label><br></strong></h4><strong>
            <input type="text" id="gen" name="gen" value="발라드"><br>


            <p>&nbsp;</p>
            <h4><label for="lyric">첫 소절, 또는 도입부를 입력해 주세요</label><br></h4><br>
            <div class="input-group flex-nowrap">
              <span class="input-group-text" id="addon-wrapping">🎶</span>
              <input width="500" class="form-control" type="text" id="lyric" name="lyric" value="여긴 동화 속 세상 네버랜드">
            </div>
            <p>&nbsp;</p>
            <input type="submit" class="btn btn-primary btn-xl" value="가사 생성하기">
           
            </strong></form></div><strong>
        </strong></header><strong>

        <section class="content-section bg-light" id="주의사항">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                        <h2>주의사항</h2>
                        <p class="lead mb-5">
                            본 서비스는 K-Digital Trainning 7,8회차 수강생이 만든 것으로 퍼가는 것은 허용되나,<br>가사의 저작권과 관련된 사항은 서비스 이용자 본인에게 책임이 있음을 알려드립니다.
                        </p>
                    </div>
                </div>
            </div>
        </section>

        <section class="content-section bg-primary text-white text-center" id="제공예정">
            <div class="container px-4 px-lg-5">
                <div class="content-section-heading">
                    <h3 class="text-secondary mb-0">comming soon</h3>
                    <h2 class="mb-5">제공 예정인 서비스</h2>
                </div>
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-screen-smartphone"></i></span>
                        <h4><strong>친구와 공유</strong></h4>
                        <p class="text-faded mb-0">카톡으로 친구와 함께 해봐요</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-pencil"></i></span>
                        <h4><strong>생성가사 수정</strong></h4>
                        <p class="text-faded mb-0">여러분이 생성된 가사를 튜닝 해봐요</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-like"></i></span>
                        <h4><strong>AI가수</strong></h4>
                        <p class="text-faded mb-0">
                            여러분의 가사를 AI가 불러줘요
                        </p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-mustache"></i></span>
                        <h4><strong>서비스센터</strong></h4>
                        <p class="text-faded mb-0">불편사항은 시정하겠습니다</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top"><svg class="svg-inline--fa fa-angle-up" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="angle-up" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" data-fa-i2svg=""><path fill="currentColor" d="M352 352c-8.188 0-16.38-3.125-22.62-9.375L192 205.3l-137.4 137.4c-12.5 12.5-32.75 12.5-45.25 0s-12.5-32.75 0-45.25l160-160c12.5-12.5 32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25C368.4 348.9 360.2 352 352 352z"></path></svg><!-- <i class="fas fa-angle-up"></i> Font Awesome fontawesome.com --></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
</strong></body>
</html>

Writing templates/input.html


In [ ]:
# %%writefile templates/result.html
# <!DOCTYPE html>
# <html>
# <head>
# <title>너의 이야기를 들려줘</title>
# <body>
#   <h1 style="text-align: center;"><strong>너의 이야기를 들려줘👂</strong></h1>
#   <h1 style="text-align: center;">생성된 가사입니다.😊</h1>
#   <p>&nbsp</p>
#   <h3 style="text-align: center;"><strong>선택 장르 : {{gen}} </strong></h3>
#     <p>&nbsp</p>
#   <h3 style="text-align: center;"><strong>입력한 사연 : {{lyric}} </strong></h3>
#   <p>&nbsp;</p>
#   <h3 style="text-align: center;"><strong>생성된 가사</strong></h3>
#   <p style="text-align: center;"><iframe src="/static/lyrictxt.txt" width="600px" height="500px" ></iframe>
# </body>

# </html>

In [16]:
%%writefile templates/result.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>너의 이야기를 들려줘</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="./assets/로고.png" />
        <link href="{{ url_for('static', path='/styles.css') }}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
    <div class="masthead d-flex align-items-center">
      <div class="container px-4 px-lg-5 text-center">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">생성된 가사입니다.</h3></div>
                                    <div class="card-body">
                                        <form>
                                            <div class="form-floating mb-6">
                                                <p style="text-align: center;"><iframe src="/static/lyrictxt.txt" text-align:'center' width="500px" height="500px"></iframe>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                        <div class="small"><a class="btn btn-primary" onclick="history.back()">첫 페이지로</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
     </div>
     </div>
    </body>

</html>

Writing templates/result.html


In [ ]:
# <p>&nbsp</p>

In [17]:
app=FastAPI()
templates = Jinja2Templates(directory="templates")
app.mount('/static', StaticFiles(directory='/content/drive/MyDrive/front-end'), name='static')

@app.get('/', response_class=HTMLResponse)
async def read_topic(request: Request):
  return templates.TemplateResponse("input.html", {"request": request})

@app.post('/topic', response_class=HTMLResponse)
async def get_topic(request: Request, gen: str = Form(...), lyric: str = Form(...)):
    # mkdlyric = ai_lyrics(gen, lyric)
    result = ai_lyrics(gen, lyric)
    # result = result.split('\n')
    fn= open(r'/content/drive/MyDrive/front-end/lyrictxt.txt').read()
    # result1 = result.replace(',', '<br>')
    # result = result.replace(',','<p>&nbsp;</p>')
    # result = result.replace(',', '<p>')
    # output = processing(result)
     
    
    return templates.TemplateResponse("result.html", {"request": request, 'gen': gen, 'lyric':lyric, 'result':result, 'fn':'/static/lyrictxt.txt'})

In [18]:
!ngrok authtoken **************

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [20]:
ngrok_tunnel = ngrok.connect(8000)
print ('Public URL:', ngrok_tunnel.public_url) 
nest_asyncio.apply()
uvicorn.run(app, host='0.0.0.0', port=8000)

Public URL: http://0dbb-34-147-49-144.ngrok.io


INFO:     Started server process [96]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)


INFO:     211.178.230.174:0 - "GET / HTTP/1.1" 200 OK
INFO:     211.178.230.174:0 - "GET /styles.css HTTP/1.1" 200 OK
INFO:     211.178.230.174:0 - "GET /js/scripts.js HTTP/1.1" 404 Not Found
INFO:     211.178.230.174:0 - "GET /yg.PNG HTTP/1.1" 200 OK
INFO:     211.178.230.174:0 - "GET /assets/%EB%A1%9C%EA%B3%A0.png HTTP/1.1" 404 Not Found


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 오늘이야 
 나의 맘을 모두 가져간 그대여 
 내게도 사랑이 온다면 
 어떤 말도 그 어떤 표현도 
 내겐 없었던 거야 
 이젠 그댈 사랑해요 
 더 이상 자신 없어도 
 너무 사랑한다는 건 
 내겐 정말 그대뿐인데 
 지금 이순간이 너무 소중해 
 나의 모든 것을 다주어도 
 모자란 내 사랑만으로 
 채워지지 않을 그대를 
 항상 나는 생각해 
 언제까지나 변함없기만을 
 우리의 사랑을 약속해 
 내가 곁에 있고픈 그대의 마음을 
 지켜주고 싶어 
 언제까지나 영원토록 
 그대만 보는 나의 사랑으로 
 어떤 말도 그 어떤 표현도 
 내겐 없었던 거야 
 이젠 그댈 사랑해요 
 이제 그대 내게 있어줘요 
 나의 마음에 오직 그대만을 
 담아두고 싶어 
 항상 나 생각해 
 언제까지나 변함없기만을 
 우리 사랑을 약속해 
 내가 곁에 있고픈 그대의 마음을 
 지켜주고 싶어 
 언제까지나 영원토록 
 그대만 보는 나의 사랑으로 
 이런 감정은 처음이라 
 알 수 없는 이 느낌 
 내가 사랑할 사람 바로 그대인걸 
 이렇게 난 너만을 사랑해 
 더 이상 자신 없어도 
 너무 사랑한다는 건 
 내겐 정말 그대뿐인데 
 지금 이순간이 너무 소중해 
 나의 모든 것을 다주어도 
 모자란 내 사랑만으로 
 채워지지 않을 그대를 
 항상 나는 생각해 
 언제까지나 변함없기만을 
 우리의 사랑을 약속해 
 내가 곁에 있고픈 그대의 마음을 
 지켜주고 싶어 
 언제까지나 영원토록 
 그대만 보는 나의 사랑으로
0.0
이건 누가 봐도 사랑일 텐데 오늘이야 
 나의 맘을 모두 가져간 그대여 
 내게도 사랑이 온다면 
 어떤 말도 그 어떤 표현도 
 내겐 없었던 거야 
 이젠 그댈 사랑해요 
 더 이상 자신 없어도 
 너무 사랑한다는 건 
 내겐 정말 그대뿐인데

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 yeah 
 yeah woohyme 
 double n four 
 double woohyme 
 woohyme baby oh 
 i just wanna show you all the time 
 coming and make love tonight 
 talk or talk or let me go 
 we must be party time with you 
 take a step closer babe 
 you girl ill make love your way 
 take a step closer babe 
 you girl ill make love your mind 
 call me bring the my heart 
 bring now 
 bring now 
 yo bring now 
 bring now 
 bring now 
 hey bring now 
 hey baby bring now 
 bring now 
 im sorry girl 
 double n four double 
 double n four double 
 i just wanna see you 
 bam bam bang bang boom banh륵 banh륵 
 we must be party time with you 
 take a step closer babe 
 you girl ill make love your way 
 take a step closer babe 
 you girl ill make love your mind 
 call me bring the my heart 
 bring now 
 bring now 
 yo bring now 
 bring no
0.9228346456692913
이건 누가 봐도 사랑일 텐데 yeah 
 yeah woohyme 
 double n four 
 double woohyme 
 woohyme baby oh 
 i just wanna show you all the time 
 coming and make love t

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 오랜만에 
 너를 만났는데 넌 왜 그리도 바보처럼 난 
 그냥 그런 여자였지 
 너를 만나려고 한 일이었는데 
 너를 너무 좋아했어 너를 너무 원했어 
 나는 너에게 너무나도 잘 어울리는데 
 이젠 널 다시 만나려 해 널 내게서 지우려 해 
 우리 사랑할 그 날들은 
 지난 추억으로 남기지만 
 너는 나만을 아껴주길 바랄 뿐야 
 다시 한번 나를 사랑해 줄래 
 난 너에게 너무나도 잘 어울리는데 
 이젠 널 다시 만나려 해 널 내게서 지우려 해 
 우리 사랑할 그 날들을 
 난 너에게 너무나 잘 어울리는데 
 이젠 널 다시 만나려 해 널 내게서 지우려 해 
 우리 사랑할 그 날들을 
 난 너에게 너무나 잘 어울리는데 
 이젠 널 다시 만나려 해 널 내게서 지우려 해 
 우리 사랑할 그 날들을 
 난 너에게 너무나도 잘 어울리는데 
 이제 널 다시 만나려고 해 널 내게서 지우려 해 
 우리 사랑할 그 날들을 
 난 너에게 너무나 잘 어울리는데 
 이제 널 다시 만나려고 해 널
0.0
이건 누가 봐도 사랑일 텐데 오랜만에 
 너를 만났는데 넌 왜 그리도 바보처럼 난 
 그냥 그런 여자였지 
 너를 만나려고 한 일이었는데 
 너를 너무 좋아했어 너를 너무 원했어 
 나는 너에게 너무나도 잘 어울리는데 
 이젠 널 다시 만나려 해 널 내게서 지우려 해 
 우리 사랑할 그 날들은 
 지난 추억으로 남기지만 
 너는 나만을 아껴주길 바랄 뿐야 
 다시 한번 나를 사랑해 줄래 
 난 너에게 너무나도 잘 어울리는데 
 이젠 널 다시 만나려 해 널 내게서 지우려 해 
 우리 사랑할 그 날들을 
 난 너에게 너무나 잘 어울리는데 
 이젠 널 다시 만나려 해 널 내게서 지우려 해 
 우리 사랑할 그 날들을 
 난 너에게 너무나 잘 어울리는데 
 이젠 널 다시

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가봐안의 
 내 맘을 사로잡는 너의 이름 
 너를 떠올리면 난 소리내 소리내어 
 울고 싶어져 
 난 지금 난 너를 사랑해 
 이제 너에게 더 다가가고 싶어 
 이제 너에게 난 다가갈게 
 이제 너에게 난 말을 할래 
 
 사랑해
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가봐 
 모아모아 모아모아 모아모아 모아모아 
 모아모아 모아 모아모아 모아모아 
 모아모아 모아 모아모아모아 모아모아 
 모아모 모아 모아모아 모아 모아모아 
 모아모 모아 모아모 모아 모아모아 모아모아 
 모아모아 모아모아 모아모아 모아모아 
 모아모 모아 모아모 모아 모아모아 
 모아모 모아 모아 모아 모아모 모아모 모아 
 모아모 모아 모아모 모아 모아 모아 
 모아모 모아 모아모 모아모 모아모아 
 모아모 모아 모아모 모아 모아서 모아모아 
 모아모 모아모 모아 모아모 모아 모아서 
 모아모 모아 모아모 모아모 모아모 모아모 모아모 모아모 
 모아모 모아 모아모 모아모 모아모 모아모
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')
아무래도 사랑인가봐 
 
 너무 많이 좋아해도 
 
 
 
 하지만 내가 싫어져 
 
 널 위해 난 아껴놨던 
 
 
 
 널 위해 전부 써둔 얘기들은 
 
 왜 내게 한것인지 
 
 
 
 정말 사랑한단 그말은 참아봤는데 
 
 
 
 내가 이렇게 사랑하는 건 
 
 너에겐 너무 큰 죄가 될 수 있단걸 알면서 
 
 
 
 날 사랑하는 것도 내 잘못이니 
 
 너의 모든걸 이해할 순 없지만 
 
 너를 위한 마음은 변치 않아 
 
 
 
 널 처음 만나는 날도 
 
 그때 나는 너만 기다려 왔던 걸 
 
 
 
 그 말을 했던 사람 
 
 내맘을 받아줄 수 없나봐 
 
 
 
 이젠 니가 미워져 
 
 널 사랑하지 않게됐어 
 
 이젠 니가 싫어져 
 
 
 
 왜왜왜왜 
 
 니가 날 미워하게 됐어 
 
 이젠 니가 싫어져 
 
 
 
 사랑해요 사랑해요 
 
 사랑해요 
 
 사랑해요 
 
 사랑해요 
 
 사랑해요 
 
 
 
 
 
 널 처음 만나는 날도 
 
 그때 나는 너만 기다려 왔던걸 
 
 
 
 그 말을 했던 사람 
 
 내맘을 받아줄 수 없나봐 
 
 
 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')
아무래도 사랑인가봐 
 its its you 
 이제는 이런 감정도 익숙해지나 봐 
 난 자꾸 널 보면 가슴이 떨려 
 이런 감정 어디서 오는가 봐 
 더 이상 참을 수 없어 
 너를 갖고 싶은 거야 
 이런 내 마음이 우 
 이 사랑을 영원할 수만 있다면 
 내가 사랑하는 네게 정말 감사해 
 내 마음 하나 몰라주는 널 
 이해 할 수는 없어도 
 지금 너에게 전부를 걸고 싶어 
 내 욕심을 못 느낀 걸까 
 난 네 앞에만 서면 
 바보 같은 웃음만 짓는데 
 이젠 네 곁이 제일 좋아 
 나를 사랑해줘 
 더 이상 견딜 수 없어 
 널 붙잡고픈 내 마음이 우 
 이 사랑을 영원할 수만 있다면 
 내가 사랑하는 네게 정말 감사해 
 내 마음 하나 몰라 주는 널 
 이해 할 수는 없어도 
 지금 너에게 전부를 걸고 싶어 
 이 사랑이 계속 멈추지 않기를 
 매일 바라고 기도했었어 
 넌 나의 baby just friend 
 i need love to anyway 
 oh i want your baby love 
 이 사랑의 영원함을 약속 할께 
 나의 마음속 깊이 널 간직해 
 널 품에 꼭 안고서 
 이대로 날 잊지 말아 줘 
 내 곁에 있어줘 
 난 이 사랑 놓을 수가 없어
0.1435523114355231
아무래도 사랑인가봐 
 its its you 
 이제는 이런 감정도 익숙해지나 봐 
 난 자꾸 널 보면 가슴이 떨려 
 이런 감정 어디서 오는가 봐 
 더 이상 참을 수 없어 
 너를 갖고 싶은 거야 
 이런 내 마음이 우 
 이 사랑을 영원할 수만 있다면 
 내가 사랑하는 네게 정말 감사해 
 내 마음 하나 몰라주는 널 
 이해 할 수는 없어도 
 지금 너에게 전부를 걸고 싶어 
 내 욕심을 못 느낀 걸까 
 난 네 앞에만 서면 
 바보 같은 웃음만 짓는데 
 이젠 네 곁이 제일 좋아 
 나를 사

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')
아무래도 사랑인가봐 
 이제 난 너의 그 눈을 
 볼 수가 있잖아 
 나의 사랑이 너의 사랑을 
 느낄 수 있을테니까 
 이제 넌 나의 영원한 사랑인거야 
 이제 넌 나의 작은 가슴 속에서 
 나를 느꼈으면 해 
 나도 지금 내맘 
 너무 뜨거우니까 
 내게 보여줘 
 너의 가슴 속에 
 나를 찾아줬으면 해 
 하지만 넌 내 곁을 떠날수는 없어 
 그 말 들을 모두 믿고 싶어 했어 
 너를 다시 한 번만이라도 보고 싶어 
 너의 그 말들로 나를 붙잡아 주겠지 
 나의 사랑이 너의 사랑을 
 느낄 수 있을거야 
 이제는 나에게 니가 너에게 사랑한다 
 말을 할 때 
 너의 곁에 있는 내가 나의 곁에 있다는 
 느낌 하나로 난 행복할 수 있어
0.0
아무래도 사랑인가봐 
 이제 난 너의 그 눈을 
 볼 수가 있잖아 
 나의 사랑이 너의 사랑을 
 느낄 수 있을테니까 
 이제 넌 나의 영원한 사랑인거야 
 이제 넌 나의 작은 가슴 속에서 
 나를 느꼈으면 해 
 나도 지금 내맘 
 너무 뜨거우니까 
 내게 보여줘 
 너의 가슴 속에 
 나를 찾아줬으면 해 
 하지만 넌 내 곁을 떠날수는 없어 
 그 말 들을 모두 믿고 싶어 했어 
 너를 다시 한 번만이라도 보고 싶어 
 너의 그 말들로 나를 붙잡아 주겠지 
 나의 사랑이 너의 사랑을 
 느낄 수 있을거야 
 이제는 나에게 니가 너에게 사랑한다 
 말을 할 때 
 너의 곁에 있는 내가 나의 곁에 있다는 
 느낌 하나로 난 행복할 수 있어
INFO:     211.178.230.174:0 - "POST /topic HTTP/1.1" 200 OK
INFO:     211.178.230.174:0 - "GET /js/scripts.js HTTP/1.1" 404 Not Found
INFO:     211.178.230.174:0 - "GET /lyrictxt.txt 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가봐하자 
 사랑만 있으면 
 its gonna be happy song 
 bingo 
 사랑만 있으면 its gonna be happy song 
 bingo 
 
 사랑한다 해도 
 정말 내게 내게도 
 사랑이란 걸 느껴 
 하지만 왜 이럴까 
 그대는 왜 나를 
 떠나야만 하는지 
 혹시 이 맘을 다 아는지 
 그대를 만나고 또 
 사랑을 알게 됐어 
 이제 그만 나를 돌아봐 
 너를 사랑하는 내가 
 어떻게 해야 할지 모르겠어 
 나는 답답해 
 이런 적 처음이야 
 내 눈이 가는 세상 속에 
 사랑밖에 난 없어 
 나를 위한 그대 향한 마음을 
 이젠 말해봐 
 나의 애인이 돼주겠니 
 사랑해요 그댈 사랑하니까 
 너무 행복한 그런 내 모습에 
 그대 행복해진 것 같아 
 bingo girl 
 사랑할래요 my love 
 그대가 있어 행복하니까 
 그대가 있어 좋은걸 
 
 왜 우리가 이렇게 
 사랑하게 된걸까 
 i think about you listen 
 that i cant you feel me oh 
 what do you think about me now 
 im ma dream with you girl 
 사랑만으로 난 충분할 수 있잖아 
 사랑만을 위해 살아가는 나야 
 yeah 
 나 하나만을 봐 
 yeah just tell me now 
 너만을 사랑해 
 널 바라보는 내가 있잖아 
 하지만 왜 너는 몰라 
 정말 나를 정말로 못 잊은거니 
 내 맘이 약한 니가 미워 
 이런 적 처음이야 
 내 눈이 가는 세상 속에 
 사랑밖에 난 없어 
 나를 위한 그대 향한 마음을 
 이젠 말해봐 
 나의 애인이 돼
0.29015544041450775
아무래도 사랑인가봐하자 
 사랑만 있으면 
 its gonna be happy song 
 bingo 
 사랑만 있으면 its gonna be happy song 
 bingo 
 
 사랑한다 해도 
 정말 내게 내게도 
 사랑이란 걸 느껴 
 하지만 왜 이럴까 
 그대는 왜 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가봐할께요 
 그 많은 사람들중에 
 왜 하필이면 내게 왔나요 
 내가 좋아 하는 사람에게도 
 내 사람이 되길 바라고 
 정말 사랑하나봐 
 너무 너무 사랑하는데 
 너무 너무 사랑해서 미워지려 해요 
 하지만 그대도 나를 좋아할까요 
 조금 더 날 봐줘 
 너무 더 바라지 마요 
 사랑해야 하는데 
 널 너무 사랑해서 
 
 어머
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가봐 예의 하자 
 이렇게 만나도 
 그 사람 생각나 왜 
 
 너의 기억속에는 항상 내가 있고 
 너는 왜 그렇게 날 아프게 해 
 너에게 내가 이 되는걸 
 
 왠지 너무 좋아 
 나를 보면 너도 항상 웃고 있잖아 
 니가 하는 모든 얘길 듣지만 
 너는 왜 이렇게 말들이 많은지 
 
 너를 만나 웃을 수 있고 
 너를 만나면 
 난 울 수 있어 
 널 위해 
 너를 만나면 
 난 더 행복해 지는걸 
 너를 만나 웃을 수 있고 
 너를 만나면 
 난 행복하단걸 
 
 repusion
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')
아무래도 사랑인가봐할께요 
 너무 보고 싶지만 이젠 안되겠어 
 정말 너만 보면 나는 가슴이 아파 
 내맘엔 니가 있어 나의 마음을 안아줘 
 사랑해 널 사랑하니까 
 너무 사랑해 
 그대에게 하고 싶은 말 
 아직 해주지 못한 말 
 사랑한단 그말 
 보고싶지만 만나지 말자 
 사랑하는 그 사람 곁에서 
 오직 한사람만 
 아껴왔던 그런 말 
 사랑해 너를 너를 사랑해 
 나를 바라보던 니 눈빛이 
 나를 보며 웃던 미소가 
 점점 내 가슴을 뛰게 해 
 날 행복하게 해 
 사랑해 널 사랑하니까 
 너무 사랑해 
 그대에게 하고 싶은 말 
 아직 해주지 못한 말 
 사랑한단 그 말 
 보고싶지만 만나지 말자 
 사랑하는 그 사람 곁에서 
 오직 한사람만 
 아껴왔던 그런말 
 사랑해 너를 너를 사랑해 
 사랑했잖아 사랑했잖아 
 정말 나를 사랑할 수 있니 
 이런 내 맘도 받아줄래 
 하지만 함께했던 시간들만큼 
 니가 바래줬으면 싶은 바보야 
 사랑해 너를 너를 사랑해
0.0
아무래도 사랑인가봐할께요 
 너무 보고 싶지만 이젠 안되겠어 
 정말 너만 보면 나는 가슴이 아파 
 내맘엔 니가 있어 나의 마음을 안아줘 
 사랑해 널 사랑하니까 
 너무 사랑해 
 그대에게 하고 싶은 말

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')
아무래도 사랑인가봐해 
 사랑노래 불러도 들려 
 사랑노래 불러도 울려 
 오늘밤에 그대에게 하고싶은 말 
 내마음 표현하긴 너무 답답해 
 나를 바라보는 너의 그 눈빛은 
 오늘도 내게로 다가오지마 
 나도 네 마음 알고 있는데 
 나의 맘도 모르는 니맘 다알아 
 그냥 나를 좋아한다고 하면 
 난 어떻게 해야겠니 
 사랑하자하면 정말이야 너와나 
 이젠 사랑하자하면 정말이야 
 사랑하자하면 정말이야 너와나 
 사랑하자하면 정말이야 
 사랑하자하면 정말이야 너와나 
 이젠 사랑하자하면 정말이야 
 사랑하자해도 정말이야 
 사랑한다고해도 오늘은 나 
 바보처럼 그냥 내가 너를 사랑할께 
 아무것도 할 수 없는 나야 
 이렇게 날 바라봐도 괜찮은지 
 항상 그 자리만 난 생각하고 있는 걸 
 이젠 나의 맘을 네게 보여 줄꺼야 
 나는 너뿐이야 
 사랑하자하면 정말이야 너와나 
 이젠 사랑하자하면 정말이야 
 사랑하자하면 정말이야 너와나 
 이젠 사랑하자하면 정말이야 
 사랑하자하면 정말이야 
 사랑하자하면 정말이야 너와나 
 이젠 사랑하자하면 정말이야 
 사랑하자하면 정말이야 너와나 
 이젠 사랑하자하면 정말이야 
 사랑하자하면 정말이야 
 사랑하자하면 정말이야 너와나 
 이젠 사랑하자하면 정말이야 
 사랑하자하면 정말이야
0.0
아무래도 사랑인가봐해 
 사랑노래 불러도 들려 
 사랑노래 불러도 울려 
 오늘밤에 그대에게 하고싶은 말 
 내마음 표현하긴 너무 답답해 
 나를 바라보는 너의 그 눈빛은 
 오늘도 내게로 다가오지마 
 나도 네 마음 알고 있는데 
 나의 맘도 모르는 니맘 다알아 
 그냥 나를 좋아한다고 하면 
 난 어떻게 해야겠니 
 사랑하자하면 정말이야 너와나 
 이젠 사랑하자하면 정말이야 
 사랑하자하면 정말이야 너와나 
 사랑하자하면 정말이야 
 사랑하자하면 정말이야 너와나 
 이젠 사랑

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 저기요 
 내 전불 주고 싶은데 
 다른 사람에게 
 난 난 나는 사랑을 하고 싶어 
 내 사랑은 너여야만 
 할 수 있는데 
 내 사랑을 네게 모두 줘도 
 난 니가 아깝지 않아 
 너를 사랑한다고 고백을 해 볼까 
 아님 이대로 내 맘을 받아줄까 
 혹시 나만의 착각인지 
 아니면 니 품에서라도 
 나의 마음 감춰 버릴까 
 너를 사랑해 사랑해 
 내가 왜 이렇게 된 거야 
 너는 한순간에 빠져 버렸어 
 지금 나의 마음을 아는 지 
 아니면 내 착각인지 
 이제는 나 밖에 모르는 내가 싫어져 
 너는 너 밖에 모르는 사람이야 
 이런 여자 만나기도 싫은데 
 너에겐 모든 게 사랑일 텐데 
 내 사랑은 항상 너 뿐이야 
 너를 사랑한다고 고백을 해 볼까 
 아님 이대로 내 맘을 받아줄까 
 혹시 나만의 착각인지 
 아니면 니 품에서라도 
 나의 마음 감춰버릴까 
 너를 사랑해 사랑해 
 난 니 곁에 있을 때 
 행복한 시간 속에 
 단 하루만 이대로 
 나에겐 네가 전부이니까 
 내게 너란 사람 없을 테니까 
 지금 나에게만 
 나를 너란 사람 없을 테니
0.0
이건 누가 봐도 사랑일 텐데 저기요 
 내 전불 주고 싶은데 
 다른 사람에게 
 난 난 나는 사랑을 하고 싶어 
 내 사랑은 너여야만 
 할 수 있는데 
 내 사랑을 네게 모두 줘도 
 난 니가 아깝지 않아 
 너를 사랑한다고 고백을 해 볼까 
 아님 이대로 내 맘을 받아줄까 
 혹시 나만의 착각인지 
 아니면 니 품에서라도 
 나의 마음 감춰 버릴까 
 너를 사랑해 사랑해 
 내가 왜 이렇게 된 거야 
 너는 한순간에 빠져 버렸어 
 지금 나의 마음을 아는 지 
 아니면 내 착각인지 
 이제는 나 밖에 모르는 내가 싫어져 
 너는 너 밖에 모르는 사람이야 
 이런 여자 만나

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 
 이젠 내가 니 맘에 문을 열기도 
 이젠 너무 든 일 
 우리 서로 함께 했었던 그 시간들 
 모두 돌려줘 이제는 우리 서로 
 하나 될 수 있던 거야 우리 정말 
 이제 너와나 정말 우리 서로 
 이제 우리 서로 잊어야 하는 일 
 우린 너무 사랑해 너무 사랑해 너무 
 우리가 하나되어 가진게 이제 
 니가 너무나도 정말 너무나도 
 고마워 내 사랑 오직 나의 전부를 바쳐도 모자라 
 니가 너무나 많이 보고 싶었어 너만 
 지금 이 순간이 행복으로 다가와 
 고마워 
 이제 너를 보는 나를 보고 있어 
 지금 이 순간 
 우리 서로 바라보고 있어 
 너에게로 난 갈 수만 있다면 
 우리 서로 가질 수만 있다면 
 이제 같은 길을 가고 싶어 
 이제는 
 이제 너와 나 정말 우리 서로 
 이제 우리 서로 잊어야 하는 일 
 우린 너무 사랑해 너무 사랑해 너무 
 우리가 하나되어 가진 게 이제 
 니가 너무나도 정말 너무나도 
 고마워 내 사랑 오직 나의 전부를 바쳐도 모자라 
 니가 너무나 많이 보고 싶었어 너만 
 지금 이 순간이 행복으로 다가와 
 고마워 
 저 하늘에 별은 너뿐 만을 밝혀 줄 거야 
 저 달빛에 달빛에 널 밝혀 줄 거야 
 이제 너는 내게 온거야 사랑해 
 너에게 너에게 너에게
0.0
이건 누가 봐도 사랑일 텐데 
 이젠 내가 니 맘에 문을 열기도 
 이젠 너무 든 일 
 우리 서로 함께 했었던 그 시간들 
 모두 돌려줘 이제는 우리 서로 
 하나 될 수 있던 거야 우리 정말 
 이제 너와나 정말 우리 서로 
 이제 우리 서로 잊어야 하는 일 
 우린 너무 사랑해 너무 사랑해 너무 
 우리가 하나되어 가진게 이제 
 니가 너무나도 정말 너무나도 
 고마워 내 사랑 오직 나의 전부를 바쳐도 모자라 
 니가 너무나 많

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 27206,  8311,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑이야 명예 
 get cherry on the maker of 
 cherry on the maker of 
 breathe in your eyes 
 on another story of uh 
 모두 너를 위한 무대가 필요해 
 널 위해서 
 더 기다려 줄게 
 조금만 기다려줄래 
 지금 만나러 갈게 
 조금만 참고 버텨볼게 
 조금만 참아볼게 
 조금만 견뎌볼게 
 아직 넌 멀리 있는데 
 조금만 지켜볼게 
 너도 나와 같다면 
 그냥 내게 와줘 
 더 기다린다면 
 더 끝까지 달려와줘 
 내게 다가와줘 
 좀 더 가까이 붙어있어줘 
 my love my love 
 love you my love 
 my love my love 
 my love oh 
 좀 더 느껴줘 
 내게 기대봐 
 더 기다릴 거야 
 이런 날 받아줘 
 my love my love 
 love you my love 
 my love 
 getcherry on the maker of 
 cherry on the maker of 
 breathe in your eyes on another story of uh 
 모두 너를 위한 무대가 필요해 
 널 위해서 
 더 기다려 줄게 
 조금만 기다려줄래 
 지금 만나러 갈게 
 조금만 참고 버텨볼게 
 조금만 참아볼게 
 좀 더 견뎌볼게 
 아직 넌 멀리 있는데 
 조금만 지켜볼게 
 너도 나와 같다면 
 그냥 내게 와줘 
 더 기다린다면 
 더 끝까지 달려와줘 
 내게 다가와줘 
 좀 더 가까이 붙어있어줘 
 my love my love 
 love you my love 
 my love oh 
 좀 더 느껴줘 
 내게 기대봐 
 더 기다릴 거야 
 이런 날 받아줘 
 my love
0.4297385620915033
이건 누가 봐도 사랑이야 명예 
 get cherry on the maker of 
 cherry on the maker of 
 breathe in your eyes 
 on another story of 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑이야 
 우리에겐 너희가 있어 
 우리에겐 너희가 있어 
 내 삶에 넌 이미 충분한 거야 
 너희들의 좋은 조연이 
 우리의 사랑 때문이란 것 
 너의 맘을 모두 열어봐 
 이제 더 이상의 슬픔은 
 너에게 없길 바래 
 우리 함께할 시간들은 
 이렇게 길진 않아 
 이젠 내가 너를 너를 너만을 
 사랑으로 안을게 
 너무 사랑해 미안해 고마워 
 너무 사랑해 미안해 미안해 
 너무 사랑해 미안해 미안해 고마워
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 27206,  8311,     3]],
       device='cuda:0')
이건 누가 봐도 사랑이야귓가지들 다 떠들어대지 
 이 세상 모든 여자들에게 하는 고백 
 너를 사랑한 동안 난 항상 고마웠었어 
 나의 마음 깊이는 
 너를 향한 나의 진심이니까 
 이토록 날 사랑하는 
 너를 감싸안으며 
 나는 다짐하고 싶어지는걸 
 내겐 너 하나 뿐이야 
 너를 바라만 보는 내게로 
 나의 사랑을 
 다시 한번 보여줘 
 이 밤은 이 밤은 
 너무 외로워 외로워 
 어둠 속에서 
 널 기다려 내게로 돌아와 
 이건 누가 봐도 사랑이야 
 이건 누가 봐도 사랑이야 
 넌 아직 나를 몰라야 하는 
 나를 지켜봐라 
 니가 없인 내 길은 없다고 
 이 순간 저 하늘에서 
 오직 너와 나만을 위한 그 노래를 불러 
 난 이제 니가 있어야 할 일만 남아 
 나의 마음 깊이는 
 너를 향한 나의 진심이니까 
 이토록 날 사랑하는 
 너를 감싸안으며 
 나는 다짐하고 싶어지는걸 
 내겐 너 하나 뿐이야 
 너를 바라만 보는 내게로 
 나의 사랑을 
 다시 한번 보여줘 
 이 밤은 이 밤은 
 너무 외로워 외로워 
 어둠 속에서 
 널 기다려 내게로 돌아와 
 이건 누가 봐도 사랑이야 
 이건 누가 봐도 사랑이야 
 너는 사랑한다 말하고 
 너는 미소짓고 있어 
 이렇게도 내가 행복한 
 너 하나 뿐이야
0.0
이건 누가

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 27206,  8311,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑이야귓속 사랑이야 
 이게 다 너의 맘 다 내꺼야 
 이건 서로가 전부야 
 이 세상 그 누구보다 더 
 너를 사랑하는 거야 
 너와 같이 할게 더 많이 많이 더 
 사랑을 할꺼야 
 난 너를 사랑해요 
 난 너를 사랑해요 
 너와 같이 할께 더 많이 많이 
 사랑이 가득하죠 
 우린 영원할꺼야 
 난 너를 사랑해요 
 난 너를 사랑해요 
 넌 너를 사랑해요 
 
 우린 서로에게 소중한 기억으로 남아줘요 
 넌 너무 잘 할거예요 
 그대를 사랑해요
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 27206,  8311,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑이야 
 이건 모두 다 모여위한거야 
 이젠 모두 함께 해요 
 이젠 모두 함께 해요 
 이젠 모두 함께해요 
 우린 모두 해내요 
 우리의 생활도 우릴 위한거죠 
 이건 모두 다 일어나야할거야 
 이건 보석의ation 
 이건 모두 다 모여있을거야 
 우리 같이 만들어볼까 
 모두 모두 모두 우리 함께
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 27206,  8311,     3]],
       device='cuda:0')
이건 누가 봐도 사랑이야 
 어머 뭐야 얘들아 이거 뭐야 이거 정말 장난 아냐 
 이거 이거 정말 정말 
 그냥 이렇게 이렇게 이런다 저췄다 
 아 아 이거 뭐 
 아 아 아니 나 좀 봐주오 
 왜 이 여자를 보면 내가 질려버려 
 뭐가 그렇게도 여자에겐 그렇게 
 난데 나도 좀 봐줄수가 있냐 
 뭐가 그렇게도 여자에겐 그렇게 
 난데 나도 좀 봐주오 
 네 앞에서 난 자꾸 자꾸만 끌려버리지 
 뭐때문에 그렇게도 자꾸만 
 왜 이 여자를 만나면 자꾸만 난 흔들리니 
 아무 남자도 난 원하고 있잖아 
 내 모든걸 가질 사람은 너만 한댔잖아 
 이제 그만 나좀봐줘 
 왜 이 여자를 보면 내가 질려버려 
 뭐가 그렇게도 여자에겐 그렇게 
 난데 나도 좀 봐주오 
 왜 이 여자를 만나도 다른 사람처럼 
 아무 여자보다 너무 좋은 너를 
 이제 더이상 난 감당할 수 없어 
 너에게로 끌려 이럼 안돼 날 책임져 
 뭐가 그렇게도 남자에겐 그렇게 
 난데 나도 좀 봐주오 
 왜 이 여자를 보면 내가 질려버려 
 뭐가 그렇게도 여자에겐 그렇게 
 난데 나도 좀 봐주오 
 네 앞에서 난 자꾸 자꾸만 끌려버리지 
 왜 이 여자를 만나면 자꾸만 난 흔들리니 
 아무 남자도 난 원하고 있잖아 
 내 모든걸 가질 사람은 너만 한렀잖아 
 이제 그만 나좀봐줘 
 왜 이 여자를 보면 내가 질려버려 
 뭐가 그렇게도 여자에겐 그렇게 
 난데 나도 좀 봐주오 
 왜

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')
아무래도 사랑인가봐안의 
 이 세상 젤 중요한 나의 맘 
 모아도 되는 너는 
 나를 바라만 보면 돼 
 넌 내맘 안줘도 난 
 너무 행복한 사람같아 
 오다다 열두시 오다다 
 십분십녀석이 
 
 모두 나를 좋아하게 될꺼야 
 넌 이런 나를 좋아하겠지 
 나는 널 사랑해 
 
 오다다 열두시 오다다 
 십 분 십분 십분만이 
 너를 사랑하게될거야 
 넌 이런 나를 좋아하겠지 
 나는 널 사랑해 
 
 이렇게 너를 
 내가 너를 좋아하고 
 이렇게 사랑하는 
 너와 내가 좋은걸 어떡해 
 오오오오오 너를 보는 순간 
 난 정말 미칠 것만 같아 
 오다다 열두시 오다다 
 십분 십분 십분만이 
 너를 사랑하게될거야 
 넌 이런 나를 좋아하겠지 
 나는 널 사랑해 
 
 오다다 열두시 오다다 
 십분 십분 십분만이 
 너를 사랑하게 될꺼야 
 넌 이런 나를 좋아하겠지 
 나는 널 사랑해 
 
 오다다 열두시 오다다 
 십분 십분 십분만이 
 너를 사랑하게 될꺼야 
 넌 이런 나를 좋아하겠지 
 나는 널 사랑해
0.0
아무래도 사랑인가봐안의 
 이 세상 젤 중요한 나의 맘 
 모아도 되는 너는 
 나를 바라만 보면 돼 
 넌 내맘 안줘도 난 
 너무 행복한 사람같아 
 오다다 열두시 오다다 
 십분십녀석이 
 
 모두 나를 좋아하게 될꺼야 
 넌 이런 나를 좋아하겠지 
 나는 널 사랑해 
 
 오다다 열두시 오다다 
 십 분 십분 십분만이 
 너를 사랑하게될거야 
 넌 이런 나를 좋아하겠지 
 나는 널 사랑해 
 
 이렇게 너를 
 내가 너를 좋아하고 
 이렇게 사랑하는 
 너와 내가 좋은걸 어떡해 
 오오오오오 너를 보는 순간 
 난 정말 미칠 것만 같아 
 오다다 열두시 오다다 
 십분 십분 십분만이 
 너를 사랑하게될거야 
 넌 이런 나를 좋아하겠지 
 나는 널 사랑해 
 
 오다다 열두시 오다다 
 십

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가봐 
 
 나도 갖고 싶어 
 너를 위해 살고 싶어 
 난 너의 모든 것을 찾고 싶었어 
 그래서 네게 말해줄래 
 너도 고백할 것 같았어 
 그래서 네게 보여줄 거야 
 나를 받아줄래요 
 이젠 말을 할 수 있어 
 난 네가 너무 좋아서 좋아 
 내 맘을 알아줘 
 너를 사랑해 
 나를 안아줘 
 널 사랑해
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  8485,     3]], device='cuda:0')
아무래도 사랑인가봐 
 우리의 만남도 그 사랑도 
 결국 우리 모두 함께라 
 난 이미 너무 다른 사람이 됐어 
 나의 맘을 나도 잘 몰라 
 그렇게도 간절한 너를 왜 몰랐을까 
 나의 사랑은 바로 
 사랑인걸 왜 모를까 
 나도 몰라 난 그냥 난 널 사랑해 
 널 정말 어떻게 널 믿겠니 
 이제와 나를 속이려고 하지마 
 
 너의 사랑도 나의 소망도 
 모두 다 널 위해 주는 것 같아 
 그렇게도 간절한 너를 왜 몰랐을까 
 나의 사랑은 바로 
 사랑인걸 왜 모를까 
 나도 몰라 난 그냥 난 널 사랑해 
 널 정말 어떻게 널 믿겠니 
 이제와 나를 속이려고 하지 마 
 나의 모든것이 널 만난 후로부터 
 
 이제와 나를 속이려고 하지마 
 너에게 많은 것을 원하지는 않아 
 나도 이젠 너를 위한 사랑을 위해 
 
 사랑이란 사랑이란 말로 
 나에게 다가왔었지 
 그렇지만 너만큼만은 쉽지가 않아 
 
 나의 사랑은 바로 
 사랑인걸 왜 모를까 
 나도 몰라 난 그냥 난 널 사랑해 
 널 정말 어떻게 널 믿겠니 
 이제와 나를 속이려고 하지마
0.0
아무래도 사랑인가봐 
 우리의 만남도 그 사랑도 
 결국 우리 모두 함께라 
 난 이미 너무 다른 사람이 됐어 
 나의 맘을 나도 잘 몰라 
 그렇게도 간절한 너를 왜 몰랐을까 
 나의 사랑은 바로 
 사랑인걸 왜 모를까 
 나도 몰라 난 그냥 난 널 사랑해 
 널 정말 어떻게 널 믿겠니 
 이제와 나를 속이려고 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  4512,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가 봐 오늘도 
 네게 전활 걸었어 
 내 맘을 훔치고서 몰래 다가간 넌 
 어떻게 하니 넌 
 날 두고 떠날 거란 
 생각 속에 잠겨있어 baby 
 너만 보면 난 맘이 약해져 
 한 마디 못해준 나 정말 미안해 baby 
 난 사랑도 못하는데 
 이런 내가 나도 싫은데 
 oh baby girl uh uh uh uh woo 
 oh baby girl uh uh uh 
 너의 사랑 앞에선 늘 다른 사람 
 하지만 또 바보처럼 니 생각에 
 바보같이 멍하니 서 있어 
 baby come back to me 
 다시 돌아온 너에게 말할래 
 이제는 놓지 않을게 
 내게서 멀어진 만큼 
 나의 곁에 더 좋은 남자가 있을 걸 알아 
 그래 더 이상 울지는 마 
 난 사랑도 못하는데 
 이런 내가 나도 싫은데 
 oh baby girl uh uh uh woo 
 oh baby girl uh uh uh 
 너의 사랑앞에선 늘 다른 사람 
 하지만 또 바보처럼 니 생각에 
 바보같이 멍하니 서 있어 
 baby girl uh uh uh woo 
 oh baby girl uh uh uh 
 너의 사랑앞에선 늘 다른 사람 
 하지만 또 바보처럼 니 생각에 
 바보같이 멍하니 서 있어 
 baby come back to me 
 다시 돌아온 너에게 말할래 
 이제는 놓지 않을게
0.31453362255965295
아무래도 사랑인가 봐 오늘도 
 네게 전활 걸었어 
 내 맘을 훔치고서 몰래 다가간 넌 
 어떻게 하니 넌 
 날 두고 떠날 거란 
 생각 속에 잠겨있어 baby 
 너만 보면 난 맘이 약해져 
 한 마디 못해준 나 정말 미안해 baby 
 난 사랑도 못하는데 
 이런 내가 나도 싫은데 
 oh baby girl uh uh uh uh woo 
 oh baby girl uh uh uh 
 너의 사랑 앞에선 늘 다른 사람 
 하지만 또 바보처럼 니 생각에 
 바보같이 멍하니 서 있어 
 baby come back to me 
 다시 돌아온 너에게 말할래 


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가 봐 오늘밤 날 잡아줘 
 나 지금 너도 몰래 널 좋아하나 봐 
 왠지 설레는 이 밤 설레는 맘 
 너만 보면 자꾸만 웃게 돼 
 네 곁에 있고 싶어 
 이런 마음 넌 몰랐음 안돼 
 나도 잘 모르겠어 어떡해야 돼 
 오늘밤 날 알아 줄래 
 오늘은 말할게 참 고마워 
 오늘밤에 꼭 나랑 영화 볼래 
 내일은 말해도 돼 
 우리 둘이라면 너랑 있다면 
 baby come to me for you 
 오늘이 가기 전에 꼭 날 안아줘 
 너와 함께 한다면 
 i can see your eyes on you 
 baby your makes me laugh 
 take something sweet tonight 
 i just wanna come to you 
 baby your makes me laugh 
 take something sweet tonight 
 i just wanna come to you 
 baby your makes me laugh 
 take something sweet tonight 
 i just wanna come to you 
 baby your makes me laugh 
 take something sweet tonight 
 i just wanna come to you 
 baby your makes me laugh 
 baby take something sweet tonight 
 내 손을 잡아줘 
 날 꼭 안아줘 내게 맡겨줘 
 이제 내게 와 어서 내게 와 
 너를 만난 순간 정말 꿈인 것만 같아 
 오늘밤 널 위해서 oh baby 
 난 너의 품에 안기고 싶어 
 너의 입술과 나의 입술이 마주친 
 그 순간을 잊지마 
 너도
0.5711947626841244
아무래도 사랑인가 봐 오늘밤 날 잡아줘 
 나 지금 너도 몰래 널 좋아하나 봐 
 왠지 설레는 이 밤 설레는 맘 
 너만 보면 자꾸만 웃게 돼 
 네 곁에 있고 싶어 
 이런 마음 넌 몰랐음 안돼 
 나도 잘 모르겠어 어떡해야 돼 
 오늘밤 날 알아 줄래

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가 봐안의 모아 
 모아 모아 모아 모아 모아 모아 모아 
 네게 말해줄게 
 왜 또 나를 떠나려 해 
 널 원하진 않아 
 내맘도 이렇게 원하나 봐 
 왜 또 나를 울려 
 너에게 말하고 싶은데 
 그말만은 하고 싶은데 
 왜 자꾸 멀어져만 갈까요 
 나는 널 붙잡아야 하나요 
 왜 날 두고 돌아서나요 
 널 원하진 않잖아 
 난 니가 필요해 
 니곁엔 바로 나야 
 더 이상 난 니곁에 
 남아있지 않게 널 사랑해 
 모아 모아 모아 모아 모아 모아 
 우리 추억 모아 모아 모아 모아 
 모아 모아 모아 모아 모아 
 모아 모아 모아 모아 모아
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  4512,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가 봐 이젠 나홀로 
 사랑이라고 말하고파 난 
 
 사랑한다고 말하긴 좀 이른 것같아 
 하지만 너와 함께했던 시간이 
 내겐 너무나도 소중하고 
 
 이렇게 외로워도 견딜 수가 있어 
 혼자라는 생각 지울 수 있어 
 
 널 사랑해 사랑해 너를 향한 이 나의 맘을 
 이 내 사랑을 너에게 주고 싶지만 
 나의 사랑도 너에게 부족하지만 
 널위해 나는 뭐든 견딜께 
 
 이런 날 이해한다 말해줘 너만은 
 
 너만 사랑해 사랑해 너를 향한 이 나의 맘을 
 이 내 사랑을 너에게 주고 싶지만 
 너의 마음 알 것 만 같아 
 널 위해 나는 뭐든 견딜께 
 
 이런날 이해한다 말해줘 너만은
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  4512,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가 봐귓속말 
 우리 둘은 사랑인가 봐 
 나도 몰래 고민해 
 네게 다가가고 싶은데 
 네가 날 바라보는 게 싫지 않아서 
 우리 사이는 멀어져가겠지 
 사랑하면 그만인 것 같아 
 우리 친구 말고 연애할래 
 이렇게 서로에게 끌리지만 
 사랑할 수 없는 걸 
 이미 알고 있어 난 너를 향한 설렘을 
 놓치고 싶지 않아 
 나의 마음을 너에게 전하고 싶은데 
 하지만 어떡하나 나는 어떻게 해야 해 
 내 마음은 커져만 가는데 왜 멍하니 서 있어 
 그 자리에서 멈춰서 있어 
 고백해도 괜찮을까 
 고백해도 괜찮을까
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  4512,     3]], device='cuda:0')
아무래도 사랑인가 봐 오늘도 난 
 너에게 할 말이 있어 
 너의 사랑 한 사람 내가 
 되고 싶어서 
 널 바라봐 나 
 처음 날 바라보던 넌 
 오늘 처음 본 사람 같아 
 내가 아닌 다른 사람과 
 나란히 누워봐 내 옆자린 널 위해 비워둘게 
 내가 맞춰 볼 테니 
 너도 몰래 서성일 수 있으니 
 더 가까이에 있어줘 baby 
 네 앞에서 아무 감정 없는 척할게 
 내 맘 아는지 내 꿈 속에 서성이네 
 더 가까이에 있어줘 baby 
 어제 오늘 내일도 오늘 같을 거야 
 우리 함께라면 
 우린 행복할 텐데 
 언제나 너로 인해 웃게 될 것 만 같아 
 이렇게 너를 사랑해줄게 
 내가 맞춰 볼 테니 
 너도 몰래 서성일 수 있으니 
 더 가까이에 있어줘 baby 
 네 앞에서 아무 감정 없는 척할게 
 내 맘 아는지 내 꿈 속에 서성이네 
 더 가까이에 있어줘 baby 
 어제 오늘 내일도 오늘 같을 거야 
 우리 함께라면 
 우린 행복할 텐데
0.04953560371517028
아무래도 사랑인가 봐 오늘도 난 
 너에게 할 말이 있어 
 너의 사랑 한 사람 내가 
 되고 싶어서 
 널 바라봐 나 
 처음 날 바라보던 넌 
 오늘 처음 본 사람 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  4512,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가 봐 하 
 널 처음 만난 
 그 순간 난 느꼈어 
 니가 내 사람이란 걸 
 그래 나도 널 보고 있었지 
 하지만 나는 느낄 수 있었어 
 사랑은 영원할 수 없어 
 
 정말 사랑하나봐 
 널 사랑하는 마음처럼 
 내겐 영원할 순 없지만 
 넌 영원할 순 없잖아 
 그래서 이젠 널 사랑해 
 이 노랠 듣고 있는 
 그대 마음을 이해해 볼게 
 그대는 나의 영원한 그대 
 날 사랑하는 만큼 
 항상 노력한다면 
 내 곁에서 영원히 
 날 지켜줘 내 사랑 언제까지나 
 그댈 위해 
 i just wanna be you just be you 
 날 사랑하는 만큼 
 나를 사랑하는 만큼 
 너를 위해서 계속 지켜줄 거야 
 i just wanna be you just be you 
 이런 내 맘 아는 걸까 
 나를 사랑하는 만큼 
 행복하게 살아줘 
 날 사랑해줘 날 사랑해줘 날 사랑해줘 
 
 이런 내맘 아는 걸까 
 나를 사랑하는 만큼 
 나를 사랑하는 만큼 
 너를 위해서 계속 지켜줄 거야 
 i just wanna be you just be you 
 날 사랑하는 만큼 
 나를 사랑하는 만큼 
 너를 위해서 계속 지켜줄 거야 
 i just wanna be you just be you 
 날 사랑하는 만큼 
 나를 사랑하는 만큼 
 나를 사랑하는 만큼 
 너를 위해서 계속 지켜줄 거야 
 i just wanna be you just be you 
 날 사랑하는 만큼 
 나를 사랑하는 만큼 
 널 위해서 계속 지켜줄 거야 
 i just wanna be you just be you 
 날 사랑하는 만큼 
 나를 사랑하는 만큼 
 나를 사랑하는 만큼 
 너를 위해서 계속 지켜줄 거야 
 i just wanna be you just be you
0.27495908346972175
아무래도 사랑인가 봐 하 
 널 처음 만난 
 그 순간 난 느꼈어 
 니가 내 사람이란 걸 
 그래 나도 널 보고 있었지 
 하지만 나는 느낄 수 있었어 
 사랑은 영원할

INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [96]


In [ ]:
#    1 # app.mount("/public", StaticFiles(directory=os.path.join(BASE_DIR, "static/public")), name="static")
# ----> 2 BASE_
# width="600px" height="500px" 