<a href="https://colab.research.google.com/github/Hongbi-Kim/Writing_lyrics/blob/master/220428_html_fastapi_ngrok.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

코랩이 구글 드라이브에 마운트돼 있어야 합니다.

구글드라이브에 front-end 숏컷이 만들어져 있어야 합니다.

결과 표시를 위해서 txt파일로 저장하는 명령을 추가했습니다.

In [ ]:
!pip install transformers

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!pip install konlpy
!git clone https://github.com/SOMJANG/Mecab-ko-for-Google-Colab.git 
%cd Mecab-ko-for-Google-Colab/
!bash install_mecab-ko_on_colab190912.sh
%cd ../

fatal: destination path 'Mecab-ko-for-Google-Colab' already exists and is not an empty directory.
/content/Mecab-ko-for-Google-Colab
Installing konlpy.....
Done
Installing mecab-0.996-ko-0.9.2.tar.gz.....
from https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
--2022-04-30 01:02:16--  https://bitbucket.org/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz
Resolving bitbucket.org (bitbucket.org)... 104.192.141.1, 2406:da00:ff00::22c0:3470, 2406:da00:ff00::22c5:2ef4, ...
Connecting to bitbucket.org (bitbucket.org)|104.192.141.1|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://bbuseruploads.s3.amazonaws.com/eunjeon/mecab-ko/downloads/mecab-0.996-ko-0.9.2.tar.gz?Signature=74OxPLosEdAED5tSsDVwPTIR5QA%3D&Expires=1651282336&AWSAccessKeyId=AKIA6KOSE3BNA7WTAGHW&versionId=null&response-content-disposition=attachment%3B%20filename%3D%22mecab-0.996-ko-0.9.2.tar.gz%22&response-content-encoding=None [following]
--2022-04-30 01:02:1

In [ ]:
from collections import Counter

In [ ]:
# 구글 드라이브에서 모델, 토크나이저 불러오기
import os
import time
import datetime
from google.colab import drive

import pandas as pd
import seaborn as sns
import numpy as np
import random
import re

import torch
from torch.utils.data import Dataset, DataLoader, random_split, RandomSampler, SequentialSampler
torch.manual_seed(42)


from transformers import GPT2LMHeadModel,  GPT2Tokenizer, GPT2Config, GPT2LMHeadModel
from transformers import AdamW, get_linear_schedule_with_warmup

# gpt3-kor-small_based_on_gpt2
from transformers import BertTokenizerFast, GPT2LMHeadModel
model = GPT2LMHeadModel.from_pretrained('/content/drive/MyDrive/gpt3_topic')
tokenizer_gpt3 = BertTokenizerFast.from_pretrained('/content/drive/MyDrive/gpt3_topic')
input_ids = tokenizer_gpt3.encode("text to tokenize")[1:]  # remove cls token

In [ ]:
#from konlpy.tag import Okt
#okt = Okt()

In [ ]:
from konlpy.tag import Mecab
mecab = Mecab()

In [ ]:
device = torch.device("cuda")
model.cuda()

seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)
model = model.to(device)

In [ ]:
model.eval()
def lyric_generator(gen, lyric):
  prompt = f"<|startoftext|> <{gen}> {lyric}"
  generated = torch.tensor(tokenizer_gpt3.encode(prompt)[1:]).unsqueeze(0)
  generated = generated.to(device)

  print(generated)

  sample_outputs = model.generate(
                                  generated, 
                                  #bos_token_id=random.randint(1,30000),
                                  do_sample=True,   
                                  top_k=50, 
                                  max_length = 350,
                                  #max_length = len(lyric) + 350,
                                  top_p=0.95, 
                                  num_return_sequences=1,
                                  repetition_penalty=1.1
                                  )
  for i, sample_output in enumerate(sample_outputs):
    # result = "{}: {}".format(i, tokenizer_gpt3.decode(sample_output, skip_special_tokens=True))
    result = tokenizer_gpt3.decode(sample_output, skip_special_tokens=True)
    result = re.sub(r"<br>", '\n', result)
    lyrictxt = open(r'/content/drive/MyDrive/front-end/lyrictxt.txt','w')
    myString = result
    lyrictxt.write(myString)
    lyrictxt.close()
    # re.sub(r'[a-z]','',result.split('\n')[-1])
    # result = re.sub(r'[a-z]','',result.split('\n')[-1])   
    # result = result[len(lyric)+1:]
    # print(re.sub(r'[a-z]','',result))
    print(result)
  return result
  # for i, sample_output in enumerate(sample_outputs):
  #   # result = "{}: {}".format(i, tokenizer_gpt3.decode(sample_output, skip_special_tokens=True))
  #   result = tokenizer_gpt3.decode(sample_output, skip_special_tokens=True)
  #   result = re.sub(r"<br>", '\n', result)
  #   # re.sub(r'[a-z]','',result.split('\n')[-1])
  #   # result = re.sub(r'[a-z]','',result.split('\n')[-1])   
  #   # result = result[len(lyric)+1:]
  #   # print(re.sub(r'[a-z]','',result))
  #   print(result)
  # return result

In [ ]:
def decide_topic(gen, lyric):

  d_topic1 = ['밤','심장','순간','날','눈','몸','숨','눈빛','머리','시선','맘','끝','손','기분','춤','시작','입술','원','준비','소리',
              '음악','느낌','때','완벽','안','위','필요','리듬','입','전']
  d_topic2 = ['눈','밤','속','순간','꿈','손','하늘','날','위','끝','숨','세상','맘','심장','시간','빛','바람','눈빛','안','기분','소리',
              '시작','별','길','때','몸','곳','노래','향기','시선']
  d_topic3 = ['남자','집','여자','매력','친구','옷','머리','생일','기분','전화','축하','노래','화장','밥','티','커피','눈치','정신','아침',
              '스타일','오늘','애','문자','몸매','분위기','얼굴','영화','오빠','번호','생일날']
  d_topic4 = ['엄마','돈','아빠','인생','나이','공부','아저씨','집','왕','애','학교','금','배','물','개','아이','맛','키','형','밥','산타',
              '오빠','몫','랩','산','동생','부모','술','라면','남']
  d_topic5 = ['춤','몸','음악','머리','인생','볼륨','준비','리듬','소리','다리','무대','돈','잔','비트','걱정','남','승리','젋음','발','폼',
              '모두','허리','땀','함성','해변','엉덩이','차','피해','게임','해결']

  b_topic1 = ['꿈','속','하늘','빛','위','끝','세상','순간','길','별','손','어둠','숨','곳','시간','시작','바람','안','눈','밤','미래','태양',
              '현실','구름','아래','날','달','내일','달빛','삶']
  b_topic2 = ['사랑','말','날','마음','생각','맘','사람','시간','모습','속','때','가슴','행복','곁','눈물','기억','세상','하루','이상','일','눈',
              '오늘','앞','끝','여자','필요','추억','친구','혼자','밤']
  b_topic3 = ['돈','집','엄마','친구','인생','나이','밥','아빠','술','오빠','차','키','남','여자','부모','잔','학교','동네','아저씨','크리스마스',
              '라면','한잔','결혼','공부','우정','애','모두','언니','배','누나']
  b_topic4 = ['춤','음악','바다','리듬','위','파도','여름','노래','몸','소리','밤','아래','태양','바람','하늘','조명','도시','볼륨','햇살','분위기',
              '기분','여행','모래','파티','걱정','일상','불빛','무대','산','해']
  b_topic5 = ['눈','맘','날','눈빛','밤','기분','심장','머리','손','순간','말','입술','시선','향기','몸','느낌','입','때','원','숨','상상','남자',
              '눈치','매력','준비','완벽','오늘','전','미소','표정']

  token = mecab.pos(lyric)
  #token = okt.pos(lyric)
  #print(token)

  word_list = []
  for t in token:
    if t[1] == 'NNG':
    #if t[1] == 'Noun':
      word_list.append(t[0])
  #print(word_list)
  
  topic_counts = []
  # Counter().moset_common(n)의 경우 같은 수의 카운트는 발생한 순으로 반환
  # 댄스 1-2-3-4-5
  if gen == '댄스':
    for word in word_list:
      if word in d_topic1:
        topic_counts.append('topic1')
      if word in d_topic2:
        topic_counts.append('topic2')
      if word in d_topic3:
        topic_counts.append('topic3')
      if word in d_topic4:
        topic_counts.append('topic4')
      if word in d_topic5:
        topic_counts.append('topic5')

  # 발라드 1-2-3-5-4
  elif gen == '발라드':
    for word in word_list:
      if word in b_topic1:
        topic_counts.append('topic1')
      if word in b_topic2:
        topic_counts.append('topic2')
      if word in b_topic3:
        topic_counts.append('topic3')
      if word in b_topic5:
        topic_counts.append('topic5')
      if word in b_topic4:
        topic_counts.append('topic4')  

  if topic_counts == []:
    topic = 'topic6'
  else:
    topic = Counter(topic_counts).most_common(1)[0][0]
  
  print(topic_counts)
  print(Counter(topic_counts).most_common())
  gen = gen + topic  

  return gen, lyric

In [ ]:
decide_topic('발라드', '사랑 하늘')

['topic2', 'topic1', 'topic4']
[('topic2', 1), ('topic1', 1), ('topic4', 1)]


('발라드topic2', '사랑 하늘')

In [ ]:
def decide_regen(input):
  val = []
  # for i in input.split('<br>'):
  for i in input.split('\n'):
    val.append(str(bool(re.search(r'[ㄱ-ㅎ|ㅏ-ㅣ|가-힣]',i))))

  eng = []
  space = []
  for char in input:
    if re.sub(r'[a-z]','',char) == "":
      eng += char
    elif char == " ":
      space += char
  eng_ratio = len(eng)/(len(input)-len(space))

  if (len(set(val[1:])) == 1) & ('False' in set(val[1:])) == True:
    print((len(set(val[1:])) == 1) & ('False' in set(val[1:])))
    print(input)
    output = 'regenerate'
  elif eng_ratio > 0.2:
    print(eng_ratio)
    print(input)
    output = 'regenerate'
  else:
    print(eng_ratio)
    output = 'pass'
  
  return output

In [ ]:
def remove_lastEng(a):
  # 마지막 줄에 영어만 있다면
  if re.sub(r'[a-z\n]','',a.split('\n')[-1]).strip() == "" :
    b = a.split('\n')[:-1]
    c = ""
    for i in b:
      if i == ' ':
        i = re.sub(r" ", "\n \n", i)
      c += i
      c = re.sub(r"  ", "\n", c)
      output = c
  else:
    output = a
  return output

In [ ]:
def ai_lyrics(gen, lyric):
  #print(decide_topic(gen,lyric)[0])
  result = lyric_generator(decide_topic(gen,lyric)[0],decide_topic(gen,lyric)[1])

  for _ in range(10):
    if len(result) < 350:
      print('길이 재생성이 필요합니다')
      result = lyric_generator(decide_topic(gen,lyric)[0],decide_topic(gen,lyric)[1])
    else:
      break

  if decide_regen(result) == 'regenerate':
    print('한글 재생성이 필요합니다.')
    #print(gen)
    output = ai_lyrics(gen, lyric)
  else:
    output = remove_lastEng(result)

  print(output)
  return

In [ ]:
!pip install fastapi nest-asyncio pyngrok uvicorn aiofiles python-multipart # 패스트API 설치

# 패스트API 관련 모듈 불러오기
from fastapi import FastAPI, Request, Form
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
import nest_asyncio
from pyngrok import ngrok

import uvicorn

# 사용할 디렉토리 만들기
!mkdir templates
!mkdir static

     |████████████████████████████████| 54 kB 1.8 MB/s 
     |████████████████████████████████| 745 kB 9.3 MB/s 
     |████████████████████████████████| 53 kB 2.2 MB/s 
     |████████████████████████████████| 10.9 MB 51.8 MB/s 
     |████████████████████████████████| 58 kB 6.6 MB/s 
     |████████████████████████████████| 79 kB 8.5 MB/s 
     |████████████████████████████████| 58 kB 6.2 MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.1.0-py3-none-any.whl size=19007 sha256=1c74e9268b473a190eb480a201d7aaed191b35482c17556c9f5855e517efbcfb
  Stored in directory: /root/.cache/pip/wheels/bf/e6/af/ccf6598ecefecd44104069371795cb9b3afbcd16987f6ccfb3
  Created wheel for python-multipart: filename=python_multipart-0.0.5-py3-none-any.whl size=31678 sha256=12a038681d47def5c2682c6edd6c6bb6a6ba98c8bc7ce1953a1888b292f6ffef
  Stored in directory: /root/.cache/pip/wheels/2c/41/7c/bfd1c180534ffdcc0972f78c5758f89881602175d48a8bcd2c
Successfully built pyngrok python-multipart


In [ ]:
#  <input class="lead mb-5" type="text" id="lyric" name="lyric" value=" 예) 여긴  동화  속  세상  네버랜드 ">

In [ ]:
%%writefile templates/input.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>너의 이야기를 들려줘</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="./assets/로고.png" />
        <link href="{{ url_for('static', path='/styles.css') }}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body id="page-top">
        <header class="masthead d-flex align-items-center">
            <div class="container px-4 px-lg-5 text-center">
                <h1>AI 작사가 에이나</h1>
                <h3 class="mb-5"><em> </em></h3>
          <form action="/topic" method="post">
            <h4><strong><label for="gen">발라드와 댄스 중 한 가지 장르를 입력해 주세요</label><br></strong></h4><strong>
            <input type="text" id="gen" name="gen" value="발라드"><br>


            <p>&nbsp;</p>
            <h4><label for="lyric">첫 소절, 또는 도입부를 입력해 주세요</label><br></h4><br>
            <div class="input-group flex-nowrap">
              <span class="input-group-text" id="addon-wrapping">🎶</span>
              <input width="500" class="form-control" type="text" id="lyric" name="lyric" value="여긴 동화 속 세상 네버랜드">
            </div>
            <p>&nbsp;</p>
            <input type="submit" class="btn btn-primary btn-xl" value="가사 생성하기">
           
            </strong></form></div><strong>
        </strong></header><strong>

        <section class="content-section bg-light" id="주의사항">
            <div class="container px-4 px-lg-5 text-center">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-lg-10">
                        <h2>주의사항</h2>
                        <p class="lead mb-5">
                            본 서비스는 K-Digital Trainning 7,8회차 수강생이 만든 것으로 퍼가는 것은 허용되나,<br>가사의 저작권과 관련된 사항은 서비스 이용자 본인에게 책임이 있음을 알려드립니다.
                        </p>
                    </div>
                </div>
            </div>
        </section>

        <section class="content-section bg-primary text-white text-center" id="제공예정">
            <div class="container px-4 px-lg-5">
                <div class="content-section-heading">
                    <h3 class="text-secondary mb-0">comming soon</h3>
                    <h2 class="mb-5">제공 예정인 서비스</h2>
                </div>
                <div class="row gx-4 gx-lg-5">
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-screen-smartphone"></i></span>
                        <h4><strong>친구와 공유</strong></h4>
                        <p class="text-faded mb-0">카톡으로 친구와 함께 해봐요</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-lg-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-pencil"></i></span>
                        <h4><strong>생성가사 수정</strong></h4>
                        <p class="text-faded mb-0">여러분이 생성된 가사를 튜닝 해봐요</p>
                    </div>
                    <div class="col-lg-3 col-md-6 mb-5 mb-md-0">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-like"></i></span>
                        <h4><strong>AI가수</strong></h4>
                        <p class="text-faded mb-0">
                            여러분의 가사를 AI가 불러줘요
                        </p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <span class="service-icon rounded-circle mx-auto mb-3"><i class="icon-mustache"></i></span>
                        <h4><strong>서비스센터</strong></h4>
                        <p class="text-faded mb-0">불편사항은 시정하겠습니다</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Scroll to Top Button-->
        <a class="scroll-to-top rounded" href="#page-top"><svg class="svg-inline--fa fa-angle-up" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="angle-up" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" data-fa-i2svg=""><path fill="currentColor" d="M352 352c-8.188 0-16.38-3.125-22.62-9.375L192 205.3l-137.4 137.4c-12.5 12.5-32.75 12.5-45.25 0s-12.5-32.75 0-45.25l160-160c12.5-12.5 32.75-12.5 45.25 0l160 160c12.5 12.5 12.5 32.75 0 45.25C368.4 348.9 360.2 352 352 352z"></path></svg><!-- <i class="fas fa-angle-up"></i> Font Awesome fontawesome.com --></a>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
</strong></body>
</html>

Writing templates/input.html


In [ ]:
# %%writefile templates/result.html
# <!DOCTYPE html>
# <html>
# <head>
# <title>너의 이야기를 들려줘</title>
# <body>
#   <h1 style="text-align: center;"><strong>너의 이야기를 들려줘👂</strong></h1>
#   <h1 style="text-align: center;">생성된 가사입니다.😊</h1>
#   <p>&nbsp</p>
#   <h3 style="text-align: center;"><strong>선택 장르 : {{gen}} </strong></h3>
#     <p>&nbsp</p>
#   <h3 style="text-align: center;"><strong>입력한 사연 : {{lyric}} </strong></h3>
#   <p>&nbsp;</p>
#   <h3 style="text-align: center;"><strong>생성된 가사</strong></h3>
#   <p style="text-align: center;"><iframe src="/static/lyrictxt.txt" width="600px" height="500px" ></iframe>
# </body>

# </html>

In [ ]:
%%writefile templates/result.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>너의 이야기를 들려줘</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="./assets/로고.png" />
        <link href="{{ url_for('static', path='/styles.css') }}" rel="stylesheet" />
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    </head>
    <body class="bg-primary">
    <div class="masthead d-flex align-items-center">
      <div class="container px-4 px-lg-5 text-center">
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                                <div class="card shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center font-weight-light my-4">생성된 가사입니다.</h3></div>
                                    <div class="card-body">
                                        <form>
                                            <div class="form-floating mb-6">
                                                <p style="text-align: center;"><iframe src="/static/lyrictxt.txt" text-align:'center' width="500px" height="500px"></iframe>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                        <div class="small"><a class="btn btn-primary" onclick="history.back()">첫 페이지로</a></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
     </div>
     </div>
    </body>

</html>

Overwriting templates/result.html


In [ ]:
# <p>&nbsp</p>

In [ ]:
app=FastAPI()
templates = Jinja2Templates(directory="templates")
app.mount('/static', StaticFiles(directory='/content/drive/MyDrive/front-end'), name='static')

@app.get('/', response_class=HTMLResponse)
async def read_topic(request: Request):
  return templates.TemplateResponse("input.html", {"request": request})

@app.post('/topic', response_class=HTMLResponse)
async def get_topic(request: Request, gen: str = Form(...), lyric: str = Form(...)):
    # mkdlyric = ai_lyrics(gen, lyric)
    result = ai_lyrics(gen, lyric)
    # result = result.split('\n')
    fn= open(r'/content/drive/MyDrive/front-end/lyrictxt.txt').read()
    # result1 = result.replace(',', '<br>')
    # result = result.replace(',','<p>&nbsp;</p>')
    # result = result.replace(',', '<p>')
    # output = processing(result)
     
    
    return templates.TemplateResponse("result.html", {"request": request, 'gen': gen, 'lyric':lyric, 'result':result, 'fn':'/static/lyrictxt.txt'})

In [ ]:
!ngrok authtoken 26P5GB752qi8SGptmLNXiDMrIsl_7GPapdJoaQNmtoGQEqbMk

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
ngrok_tunnel = ngrok.connect(8000)
print ('Public URL:', ngrok_tunnel.public_url) 
nest_asyncio.apply()
uvicorn.run(app, host='0.0.0.0', port=8000)

Public URL: http://ce7f-35-243-130-129.ngrok.io


INFO:     Started server process [81]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)


INFO:     182.172.56.228:0 - "GET / HTTP/1.1" 200 OK
INFO:     182.172.56.228:0 - "GET /styles.css HTTP/1.1" 200 OK
INFO:     182.172.56.228:0 - "GET /js/scripts.js HTTP/1.1" 404 Not Found
INFO:     182.172.56.228:0 - "GET /js/scripts.js HTTP/1.1" 404 Not Found
INFO:     182.172.56.228:0 - "GET /yg.PNG HTTP/1.1" 200 OK
INFO:     122.36.106.155:0 - "GET / HTTP/1.1" 200 OK
INFO:     122.36.106.155:0 - "GET /js/scripts.js HTTP/1.1" 404 Not Found
INFO:     122.36.106.155:0 - "GET /styles.css HTTP/1.1" 200 OK
INFO:     122.36.106.155:0 - "GET /yg.PNG HTTP/1.1" 200 OK
INFO:     122.36.106.155:0 - "GET /assets/%EB%A1%9C%EA%B3%A0.png HTTP/1.1" 404 Not Found


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


['topic1', 'topic2', 'topic1', 'topic2']
[('topic1', 2), ('topic2', 2)]
['topic1', 'topic2', 'topic1', 'topic2']
[('topic1', 2), ('topic2', 2)]
tensor([[42000, 42003, 21036, 23470,  5036, 16599,  2878,  8011, 14200,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


여긴 동화 속 세상 네버랜드 
 여기 모든 것 함께 노래해줘 
 이 사랑의 이끄는 저곳으로 
 너에게 닿기를 바래 
 사랑한다는 말이 너무 흔해서 들어 
 이 말을 꼭 하고 싶었어 
 사랑한단 말은 아직 많이 모자라지만 
 정말 난 그런 말이 될 수 없을 것만 같아 
 오늘은 오늘은 정말 말할꺼야 
 사랑한다는 말이 너무 흔해서 들어 
 우리가 사랑을 할 수 없다는게 너무 싫지만 
 그래도 그냥 안아주면 되는 걸까 
 사랑한다는 말이 너무 흔해서 들어 
 이 말을 꼭 하고 싶었어 
 사랑한다는 말이 너무 흔해서 들어 
 우리가 사랑을 할 수 없다는게 너무 싫지만 
 그래도 그냥 안아주면 되는 걸까
길이 재생성이 필요합니다
['topic1', 'topic2', 'topic1', 'topic2']
[('topic1', 2), ('topic2', 2)]
['topic1', 'topic2', 'topic1', 'topic2']
[('topic1', 2), ('topic2', 2)]
tensor([[42000, 42003, 21036, 23470,  5036, 16599,  2878,  8011, 14200,     3]],
       device='cuda:0')
여긴 동화 속 세상 네버랜드 
 음악하는 사람들 모여 다같이 노래 하는 곳 
 꿈의 나라 꿈의 나라 꿈의 나라 
 환상의 나라 꿈의나라 꿈의 나라 
 이 순간을 즐겨야해 모든 사람 사랑 하고파 
 사랑하는 마음을 다 함께 전할 수 있고 
 세상 가장 친한 친구도 모두함께 손을 잡고 
 꿈꾸는 나라 꿈의 나라 꿈의 나라 
 환상의 나라 꿈의 나라 꿈의 나라 
 이 순간을 즐겨야해 모든 사람 사랑 하고파 
 사랑하는 마음을 다 함께 전할 수 있고 
 세상 가장 친한 친구도 모두함께 손을 잡고 
 꿈꾸는 나라 꿈의 나라 꿈의 나라 
 이 순간을 즐겨야해 모든 사람 사랑 하고파 
 사랑하는 마음을 다 함께 전할 수 있고 
 세상 가장 친한 친구도 모두함께 손을 잡고 
 꿈꾸는 나라 꿈의 나라 
 꿈꾸며 날아보자 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


['topic1', 'topic2', 'topic1', 'topic2']
[('topic1', 2), ('topic2', 2)]
['topic1', 'topic2', 'topic1', 'topic2']
[('topic1', 2), ('topic2', 2)]
tensor([[42000, 42003, 21036, 23470,  5036, 16599,  2878,  8011, 14200,     3]],
       device='cuda:0')
여긴 동화 속 세상 네버랜드 
 난 그냥 그 자리에서 
 니 이름을 불러봐 
 마법처럼 스며드는 이 순간 
 햇살 내리듯 눈부신 순간 
 그래 너와 나 우리 둘이야 
 니가 좋아 좋아 
 너만 있다면 좋아 좋아 
 이 밤이 가기 전에 
 나랑 같이 갈래 
 우리 둘은 영원해 
 처음 보면 첫 느낌 그대로 
 널 사랑한단 그 말 느낄 수가 있어 
 끌린 듯 끌린 듯 끌린 듯 끌리는 이 시간 
 난 이렇게 우리 함께해 사랑해 
 저 멀리 반짝이는 저 별빛과 
 반짝이는 니 눈을 보면 설레 
 꿈속에도 꿈속에도 더는 볼 수 없어 
 사랑스런 입술과 나를 감싸는 목소리 
 내겐 이 모든 걸 니가 원하기 때문에 
 우린 이렇게 우리 사랑하게 되는 거야 
 모든 것들이 변해도 
 영원히 우리는 행복할거야
0.0
여긴 동화 속 세상 네버랜드 
 난 그냥 그 자리에서 
 니 이름을 불러봐 
 마법처럼 스며드는 이 순간 
 햇살 내리듯 눈부신 순간 
 그래 너와 나 우리 둘이야 
 니가 좋아 좋아 
 너만 있다면 좋아 좋아 
 이 밤이 가기 전에 
 나랑 같이 갈래 
 우리 둘은 영원해 
 처음 보면 첫 느낌 그대로 
 널 사랑한단 그 말 느낄 수가 있어 
 끌린 듯 끌린 듯 끌린 듯 끌리는 이 시간 
 난 이렇게 우리 함께해 사랑해 
 저 멀리 반짝이는 저 별빛과 
 반짝이는 니 눈을 보면 설레 
 꿈속에도 꿈속에도 더는 볼 수 없어 
 사랑스런 입술과 나를 감싸는 목소리 
 내겐 이 모든 걸 니가 원하기 때문에 
 우린 이렇게 우리 사

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


['topic2', 'topic2']
[('topic2', 2)]
['topic2', 'topic2']
[('topic2', 2)]
tensor([[42000, 42010, 21036, 23470,  5036, 16599,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


여긴 동화 속 세상 
 서로의 마음에 깊이 스미고 
 신비로운 마법에 빠진 순간 
 사랑이란 magic song 
 모든 이 magic magic feeling 
 서로의 가슴에 불이 생기네 
 아름다운 네 모습 순수한 미소 
 이 세상 어느 곳에서도 나올 수 없네 
 서로의 사랑을 가득 안고 
 서로에게 채워주는 곳 
 우리가 꿈꾸는 무대 그 곳에 
 우리의 기쁨과 슬픔 그리고 그 웃음 
 모든 것 모든 것들 위해 
 영원히 함께 할 수 있다면 
 소망 소망 소망 소망 
 소망 소망 소망 소망 
 소망 소망 소망 소망 
 행복의 꿈
길이 재생성이 필요합니다
['topic2', 'topic2']
[('topic2', 2)]
['topic2', 'topic2']
[('topic2', 2)]
tensor([[42000, 42010, 21036, 23470,  5036, 16599,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


여긴 동화 속 세상듣지 
 its been a while 
 마법처럼 네게 물들어 너만 보면 두근대지 
 feel like an angel 
 마치 깜짝 선물 같아 
 youre my favorite 
 너의 예쁜 두 눈에 빠져들걸 
 내 맘이 녹아내려 
 모든 게 펼쳐질 것만 같지 
 네가 너무 좋아져 
 i love you 
 youre everything to me 
 이 마법처럼 내게 다가와 
 네 속에 영원히 잠들고 싶어 
 love you 
 take my heart 
 나만을 보는 맑은 눈빛 
 더 아름다운 걸 
 take my heart 
 나만이 느낄 수 있는 걸 
 나의 마법에 빠져들어 
 love you 
 oh oh oh oh oh 
 사랑 가득 담아 너에게 줄게 
 이 세상에 너뿐이야 
 love you 
 take my heart 
 사랑을 채워줄게 
 너를 만나 너로 인해 난 행복해져 
 oh oh oh oh oh 
 사랑 가득 담아 너에게 줄게 
 이 세상에 너뿐이야 
 너 하나로 가득해 
 내 마음이 행복이 전부 널 바라보잖아 
 im still in your heart 
 fell in love with you 
 feel like an angel 
 마법처럼 네게 물들어 
 i love you 
 youre everything to me 
 이 마법처럼 내게 다가와 
 네 속에 영원히 잠들고 싶어 
 love you 
 take my heart 
 나만을 보는 맑은 눈빛 
 더 아름다운 걸 
 take my heart 
 나만이 느낄 수 있는 걸 
 나의 마법에 빠져들어 
 love you 
 oh oh oh oh o
0.4570446735395189
여긴 동화 속 세상듣지 
 its been a while 
 마법처럼 네게 물들어 너만 보면 두근대지 
 feel like an angel 
 마치 깜짝 선물 같아 
 youre my favorite 
 너의 예쁜 두 눈에 빠져들걸 
 내 맘이 녹아내려 
 모든 게 펼쳐질 것만 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


['topic2', 'topic2']
[('topic2', 2)]
['topic2', 'topic2']
[('topic2', 2)]
tensor([[42000, 42010, 21036, 23470,  5036, 16599,  2878,  8011, 14200,     3]],
       device='cuda:0')
여긴 동화 속 세상 네버랜드 
 노래 불러주오 아 아 아 아 
 신비의z 모험을 떠나볼래 
 그 누구도 알 수 없게 속삭여줘 
 마법처럼 모든 걸 이뤄줄 테니 
 신비한 마법처럼 모든걸 다 보여줄 테니 
 신비한 기적처럼 모든 걸 감싸 안을 테니 
 신비한 마법처럼 모든 걸 알려줄 테니 
 여긴 동화 속 세상 네버랜드 
 응원하고 응원해야만 해 
 우리가 찾는 꿈이 있는 그곳 
 그곳에서 우리 함께 노래하고 춤을 춰 
 꿈의 나라로 데려가 주는 그대와 
 아침 해와 달이 비추는 곳에서 
 이 세상이 끝나는 그날까지 사랑해요 
 해가 뜨면 시작 되는 하루처럼 
 매일 매일 사랑할게 
 마법처럼 모든 걸 이뤄줄 테니 
 신비한 마법처럼 모든 걸 다 보여줄 테니 
 신비한 기적처럼 모든 걸 감싸 안을 테니 
 신비한 마법처럼 모든 걸 알려줄 테니 
 신비한 마법처럼 모든 걸 감싸 안을 테니 
 여기 저기 어지럽게 흩어져 버린 
 이 세상을 아름답게 바꿔줄 너와 
 신비한 마법처럼 모든 걸 알려줄 테니 
 신비한 마법처럼 모든 걸 더 보여 줄 테니 
 신비한 마법처럼 모든 걸 알게 될 테니 
 신비한 마법처럼 모든 걸 들려 줄 테니 
 신비한 마법처럼 
 신비한 마법처럼 모두 열어 줄 테니
0.002369668246445498
여긴 동화 속 세상 네버랜드 
 노래 불러주오 아 아 아 아 
 신비의z 모험을 떠나볼래 
 그 누구도 알 수 없게 속삭여줘 
 마법처럼 모든 걸 이뤄줄 테니 
 신비한 마법처럼 모든걸 다 보여줄 테니 
 신비한 기적처럼 모든 걸 감싸 안을 테니 
 신비한 마법처럼 모든 걸 알려줄 테니 
 여긴 동화 속 세상 네버랜드 
 응원하고

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014,  2852,  8061, 14057, 14042, 14672, 36940, 17329, 13975,
          2199,     3]], device='cuda:0')
너와 함께 하고 싶은 일들을 상상하는 게 
 보석을 빛의 속도로 붉게 태울래 
 우리만의 축제를 즐길 수 있도록 
 lets go 
 너와 함께 하고 싶은 일들을 상상하는 게 
 가치 있는 길이지만 우리의 꿈은 이루어질 순 없어 
 너와 함께한 모든 날들이 그저 꿈이기를 
 
 너를 알기 전에 내가 먼저 말을하면 안될까 
 나는 정말 불안할 거야 
 너와의 행복이 어떻게 될지 
 나는 알 수가 없어 
 내 맘 어떻게 표현할지 몰라 
 
 너와 함께 하고 싶은 일들을 상상하는 게 
 가치 있는 길이지만 우리의 꿈은 이루어질 순 없어 
 너와 함께한 모든 날들이 그저 꿈이기를 
 
 너와 함께 하고 싶은 일들을 상상하는 게 
 가치 있는 길이지만 우리의 꿈은 이루어질 순 없어 
 너와 함께한 모든 날들이 그저 꿈이기를
0.021505376344086023
너와 함께 하고 싶은 일들을 상상하는 게 
 보석을 빛의 속도로 붉게 태울래 
 우리만의 축제를 즐길 수 있도록 
 lets go 
 너와 함께 하고 싶은 일들을 상상하는 게 
 가치 있는 길이지만 우리의 꿈은 이루어질 순 없어 
 너와 함께한 모든 날들이 그저 꿈이기를 
 
 너를 알기 전에 내가 먼저 말을하면 안될까 
 나는 정말 불안할 거야 
 너와의 행복이 어떻게 될지 
 나는 알 수가 없어 
 내 맘 어떻게 표현할지 몰라 
 
 너와 함께 하고 싶은 일들을 상상하는 게 
 가치 있는 길이지만 우리의 꿈은 이루어질 순 없어 
 너와 함께한 모든 날들이 그저 꿈이기를 
 
 너와 함께 하고 싶은 일들을 상상하는 게 
 가치 있는 길이지만 우리의 꿈은 이루어질 순 없어 
 너와 함께한 모든 날들이 그저 꿈이기를
INFO:     211.178.230.174:0 - "POST 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 27723, 37484, 21594,  8082, 13973, 41032, 13983,     3]],
       device='cuda:0')
너의 행동에 설레어하고 뒤척이다 
 
 마치 우리 둘만의 영화 처럼 
 
 내 심장 깊은 곳에 자꾸 너만 맴돌아 
 
 이런 내 맘 어떻게 전할까 
 
 너를 사랑하고 있어 
 
 너도 날 좋아할까 나처럼 또 망설이겠지 
 
 날 좋아 할 사람 있니 내게 다가와 줘 
 
 사랑해요 나의 소망은 오직 너 하나 뿐이야 
 
 나는 그대에게 빠져있고 싶어 
 
 오직 너뿐야 너에게 푹 빠져버린걸 
 
 
 
 너의 관심에 설레고 우울할 때 난 
 
 항상 이 되 주고 싶은 네 맘 
 
 네게 줄 수 있다면 나 행복할 텐데 
 
 이제는 네게 말을 할거야 
 
 너의 매력에 푹 빠져버린 내 맘을 
 
 널 좋아한다고 너만을 사랑한다고 
 
 너와 함께라면 더 이상 망설이지 않아 
 
 너의 매력에 푹 빠져버린 내 맘을 
 
 
 
 너의 매력에 푹 빠져버린 나를 
 
 사랑해 나의 사랑 너를 사랑해 
 
 내 사랑을 꼭 믿고 있다면 너 후회 하지 말아줘 
 
 난 너를 정말 사랑해 사랑해 사랑해 
 
 이 두 마디가 너에겐 얼마나 들게 될지 
 
 아직은 너와 난 너무나 먼 사이라는 걸 
 
 너의 매력에 빠져버렸어 너무 소중한 너를 
 
 나는 너의 매력에 취해버렸어 
 
 매일 밤 나는 너를 상상해 
 
 너의 두 눈을 보며 
 
 사랑에 빠져버렸어 오 
 
 내 곁에 있어줘 나만의 그댄 말야
0.0
너의 행동에 설레어하고 뒤척이다 
 
 마치 우리 둘만의 영화 처럼 
 
 내 심장 깊은 곳에 자꾸 너만 맴돌아 
 
 이런 내 맘 어떻게 전할까 
 
 너를 사랑하고 있어 
 
 너도 날 좋아할까 나처럼 또 망설이겠지 
 
 날 좋아 할 사람 있니 내게 다가와 줘 
 
 사랑해요 나의 소망은 오직 너 하나 뿐이야 
 
 나는 그대에게 빠져있고 싶어 
 
 오직

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 27723, 37484, 21594,  8082, 13973, 41032, 13983,     3]],
       device='cuda:0')
너의 행동에 설레어하고 뒤척이다 
 내가 아닌 다른 사람에게 얘기해 
 난 너를 좋아한단 말도 하지 않았어 
 니가 좋아한단 말을 먼저 할 줄은 
 정말 나는 못 느꼈어 
 그냥 너를 너무 좋아해서 
 니 마음 받아줄래 이제라도 말할게 
 그냥 나를 좋아해도 좋아 
 네게 조금씩 다가갈래 
 그냥 나는 너였으면 좋겠어 
 그냥 너를 좋아하면 됐어 
 네 맘에 들어갈래 이젠 고백할게 
 너는 어때 나의 모든 것을 다줄 거야 
 너의 그 한마디에 두근거리고 두근거리고 
 너라는 세상에 빠져있는 날 볼 때면 
 이렇게 나도 모르게 미소짓고 
 난 하루하루를 너로 가득히 채웠어 
 그냥 내게만 더 해줘 더 사랑해서 
 이제라도 말할게 
 그냥 나를 좋아해도 좋아 
 네게 조금씩 다가갈래 
 그냥 나는 너였으면 좋겠어 
 그냥 나는 너였으면 좋겠어 
 그냥 너는 너였으면 좋겠어
0.0
너의 행동에 설레어하고 뒤척이다 
 내가 아닌 다른 사람에게 얘기해 
 난 너를 좋아한단 말도 하지 않았어 
 니가 좋아한단 말을 먼저 할 줄은 
 정말 나는 못 느꼈어 
 그냥 너를 너무 좋아해서 
 니 마음 받아줄래 이제라도 말할게 
 그냥 나를 좋아해도 좋아 
 네게 조금씩 다가갈래 
 그냥 나는 너였으면 좋겠어 
 그냥 너를 좋아하면 됐어 
 네 맘에 들어갈래 이젠 고백할게 
 너는 어때 나의 모든 것을 다줄 거야 
 너의 그 한마디에 두근거리고 두근거리고 
 너라는 세상에 빠져있는 날 볼 때면 
 이렇게 나도 모르게 미소짓고 
 난 하루하루를 너로 가득히 채웠어 
 그냥 내게만 더 해줘 더 사랑해서 
 이제라도 말할게 
 그냥 나를 좋아해도 좋아 
 네게 조금씩 다가갈래 
 그냥 나는 너였으면 좋겠어 
 그냥 나는 너였으면 좋겠어 
 그냥 너는 너였으면 좋겠어
INFO:  

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 27723, 37484, 21594,  8082, 13973, 41032, 13983,     3]],
       device='cuda:0')
너의 행동에 설레어하고 뒤척이다 
 너의 입술 위 내 입술 위에 내 입술이 닿을 때 
 왠지 모를 짜릿한 느낌이 
 너의 모습에 끌려만 가 
 너무 예쁜 모습에 나는 그만 그만 
 너무 예쁜 모습에 나는 그만 그만 
 나는 너를 처음 보면 반했어 
 나를 보는 그 눈빛과 그 얼굴때문에 
 나도 모르게 이끌려버렸어 
 너무 끌렸어 나도 모르게 빠져버렸어 
 나의 마음 속에 너라는 환상이 
 자꾸 점점 날 가슴 뛰게 만들잖아 
 너무 예쁜 모습에 나는 그만 그만 
 너무 예쁜 모습에 나는 그만 그만 
 너무 예쁘게 다가온 너 때문에 나도 모르게 끌려가 
 너무 예뻐도 나를 봐봐 느껴봐 느껴봐 
 날 바라봐 지금 
 너의 미소에 빠져드는 순간 
 다시 한 번 사랑에 빠졌나봐 
 너무 예쁜 모습에 나는 그만 그만 
 너무 예뻐진 모습 나는 그만 그만 
 너무 예쁘게 다가온 너 때문에 나도 모르게 이끌려버렸어 
 너무 잘났어 나도 모르게 빠져버렸어
0.0
너의 행동에 설레어하고 뒤척이다 
 너의 입술 위 내 입술 위에 내 입술이 닿을 때 
 왠지 모를 짜릿한 느낌이 
 너의 모습에 끌려만 가 
 너무 예쁜 모습에 나는 그만 그만 
 너무 예쁜 모습에 나는 그만 그만 
 나는 너를 처음 보면 반했어 
 나를 보는 그 눈빛과 그 얼굴때문에 
 나도 모르게 이끌려버렸어 
 너무 끌렸어 나도 모르게 빠져버렸어 
 나의 마음 속에 너라는 환상이 
 자꾸 점점 날 가슴 뛰게 만들잖아 
 너무 예쁜 모습에 나는 그만 그만 
 너무 예쁜 모습에 나는 그만 그만 
 너무 예쁘게 다가온 너 때문에 나도 모르게 끌려가 
 너무 예뻐도 나를 봐봐 느껴봐 느껴봐 
 날 바라봐 지금 
 너의 미소에 빠져드는 순간 
 다시 한 번 사랑에 빠졌나봐 
 너무 예쁜 모습에 나는 그만 그만 
 너

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  4512,     3]], device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


아무래도 사랑인가 봐 말라 
 배 아플 때도 참고 참아 
 난 왠지 그냥 기분이 좋아 
 이렇게 좋아도 되는 걸까 
 내게도 이런 느낌일 줄 몰랐어 
 왜 이렇게 변했을까 
 내겐 너만 그대로야 
 니 맘은 언제나 변할 거야 
 난 내가 봐도 정말 좋은 걸 어떡해 
 내가 봐도 니가 좋아져 정말 
 그 어떤 말도 나의 마음을 전할 수 없어 
 이제 그만 이제 그만해 
 너의 모든 게 나에게는 너무 달콤해 
 난 원래 내가 봐도 정말 좋은 걸 어떡해 
 그 어떤 말도 나의 마음을 전할 수 없어 
 이젠 널 정말 좋아하기 싫어 
 이제 그만 이제 그만해 
 너의 모든 게 나에게는 너무 달콤해 
 우린 정말 이렇게 좋은 걸
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 15397, 14366, 14674,  4512,     3]], device='cuda:0')
아무래도 사랑인가 봐 아침 일찍 일어나 
 거울 보며 웃는 여자애들 
 너무 이상하지 나는 정말 바보인가봐 
 어제도 밤 늦도록 울었어 
 이런 바보가 참 이상해 
 사랑도 모르고 상처를 주고 
 혼자 외로울 텐데 
 
 니가 떠나 버린 건 
 정말 미안해 
 그래서 내게 온거야 
 넌 나 하나뿐인 줄 알았었는데 
 다른 누구도 줄 수 없는 걸 
 이렇게 난 몰랐어 
 내가 이러는 게 미워서 
 이젠 너를 다시 볼 순 없을까 
 아무리 나를 울려도 
 어쩔 수가 없을 텐데 
 왜 하필 내 앞에 나타나서 
 울고 있는 거야 baby 
 내가 이러는 게 미워서 
 이제는 너란 사람 
 나 같은 것은 다 잊고 
 
 니가 떠나 버린 건 
 정말 미안해 
 그래서 내게 온거야 
 넌 나 하나뿐인 줄 알았었는데 
 다른 누구도 줄 수 없는 걸 
 이렇게 난 몰랐어 
 내가 이러는 게 미워서 
 이젠 너를 다시 볼 순 없을까 
 아무리 나를 울려도 
 어쩔 수가 없을 텐데 
 왜 하필 내 앞에 나타나서 
 울고 있는 거야 baby 
 내가 이러는 게 미워서 
 이제는 너란 사

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 너와 
 내 모든 걸 줄 수 있는데 
 네 곁에는 다른사람 있어 
 왜 이래 내 맘을 
 이렇게 많이 아파했는데 
 난 정말 못됐어 
 내게 이러지마 
 이렇게 아프게 할 줄 몰랐잖아 
 널 들게만 했었지 
 이제는 내게와 줘 
 baby lets get in to my house 
 i love you love you 너 없인 정말 
 살아갈 수 없어 
 너와의 추억들 모두 잊을꺼야 
 baby lets get in to my house 
 i love you love you 난 정말 
 죽을 만큼 들어 
 내가 원한 게 넌 아닐테니깐 
 너 아닌 누굴 또 사랑해 
 어떻게 해야 해 
 이 세상 끝까지 날 내버려둘꺼야 
 이제 난 널 떠나야해 
 내게 이러지마 
 이렇게 아프게 할줄 몰랐잖아 
 널 들게만 했었지 
 이제는 내게와 줘 
 baby lets get in to my house 
 i love you love you 너 없인 정말 
 살아갈 수 없어 
 너와의 추억들 모두 잊을꺼야 
 baby lets get in to my house 
 i love you love you 난 정말 
 죽을만큼 들어 
 얼마나 울어야 니가 돌아올까 
 그리움에서 영원히 떠나질 않아 
 나를 놓지 마 
 baby lets get in to my house 
 i love you love you 너 없인 정말 
 살아갈수 없어 
 너와의 추억들 모두 잊을꺼야 
 baby lets get in to my house 
 i love you love you 난 정말 
 죽을만큼 들어
0.4
이건 누가 봐도 사랑일 텐데 너와 
 내 모든 걸 줄 수 있는데 
 네 곁에는 다른사람 있어 
 왜 이래 내 맘을 
 이렇게 많이 아파했는데 
 난 정말 못됐어 
 내게 이러지마 
 이렇게 아프게 할 줄 몰랐잖아 
 널 들게만 했었지 
 이제는 내게와 줘 
 baby lets get in to my house 
 i love you love you 너 없인 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 yeah 
 we got the trouble maker 
 you got the true loves girl 
 dont even know about this 
 listen how we just blah uh 
 listen now and it goes listen to 
 the falling star show me baby 
 lets heart play the music baby 
 이 느낌 그대로 make it better 
 i will loving you 
 내 모든걸 다 바쳐도 아깝지 않아 
 내 곁에만 있어줘 
 you know i need you love youre so sweet 
 내 손을 잡아줘 
 you know i want your love 
 come on 
 come on come on 
 baby i need your love youre so sweet 
 oh im the one for you baby 
 이 모든 걸 다 바쳐도 넌 필요 없어 
 난 니가 필요 해 
 im the only for you 
 난 니곁에 있으면 
 정말 행복해 forever young baby 
 이건 누가 봐도 사랑일 텐데 yeah 
 we got the trouble maker 
 you got the true loves girl 
 dont even know about this 
 listen how we just blah uh 
 listen now and it goes listen to 
 the falling star show me baby 
 나 널 위해 
 내 뭐든 다 바칠게 oh baby 
 내 모든걸 다 바쳐도 너 뿐이야 
 내 곁에만 있어줘 
 you kn
0.7645211930926217
이건 누가 봐도 사랑일 텐데 yeah 
 we got the trouble maker 
 you got the true loves girl 
 dont even know about this 
 listen how

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 지금 넌 왜 
 우리 두 사람 서로는 또 잘 맞는 걸 어떡해 
 이젠 어떡하니 이젠 어떡할까 
 우린 이제 서로 정말 행복했잖아 
 다시 만나 다시 만나 예전처럼 너를 
 너에겐 미안해 모두다 너와 나 둘 다 
 이제는 정말 다신 믿지 않아 
 이젠 너를 믿지 않아 이젠 내가 아파 
 이제 우리 두 사람 서로는 또 잘 맞는 걸 어떡해 
 이젠 어떡하니 이젠 어떡할까 
 우린 이제 서로 정말 행복했잖아 
 다시 만나 다시 만나 예전처럼 너를 
 나는 이렇게 나도 너를 사랑하는데 
 이미 우린 끝나버린 사랑은 싫어 
 이제 제발 그만 해 내가 너를 버렸어
길이 재생성이 필요합니다
[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 baby 
 yo listen about the sound 
 double things in this world 
 
 hey hey girl 
 take one more time 
 one two for the right 
 
 내게로 come on now 
 너의 그 눈빛 
 너의 니 얼굴 
 난 다 갖고 싶은데 
 
 yo listen girl 
 show me that you love me 
 내게 한걸음만 더 다가와줄래 
 아직 사랑인 것 같은데 
 나 몰래 빠져들면 어떡해 
 내가 좀 부족한 것 같아 
 oh girl you know what i want 
 나만 몰랐었던 니가 너무 궁금해 
 이제 내 사랑 시작인데 uh 
 love me come and get me boy 
 나도 모르겠어 
 oh huh uh 
 boy boy boy 
 너만 보면 두근두근 뛰는걸 
 my boy my boy 
 날 바라보는 순간 
 날 좋아하는 너 
 its shiny hot hot 
 i cant wait 
 you are ma ma ma ma ma mam girl 
 lets start go girl 
 when you tell me a speak of saxio 
 hey hey girl 
 touch me my boy 
 내 매력에 넌 끌렸나 봐 
 나 밖에 없는 걸 oh 
 you are give it to me girl 
 내가 좀 부족한 것 같아 
 oh girl you know what i want 
 나만 몰랐었던 니가 너무 궁금해 
 이제 내 사랑 시작인데 uh 
 love me come and get me boy 
 나도 모르겠어 

0.6304347826086957
이건 누가 봐도 사랑일 텐데 baby 
 yo listen about the sound 
 double things in this world 
 
 hey hey girl 
 take one more time 
 one two for the right

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 
 난 너와의 얘기라면 전부 믿을 텐데 
 내가 먼저 만나지 말 것을 그랬어 
 그 말이 뭐가 중요한지를 모르겠어 
 이젠 나 혼자서 너를 보내야 해 
 네가 없으면 살아갈 수 없는데 
 내가 먼저 연락하지 마 
 우리 끝난 거야 
 이미 다른 사랑도 
 내가 먼저 시작도 안 했는데 
 이렇게 널 놓치는데 
 이렇게 넌 나에게서 멀어져 가는 걸 
 난 어떡해 어떻게 해야 해 
 너에겐 너무도 많은 걸 알고 있는데 
 이렇게 넌 나에게서 멀어져 가는걸 
 넌 다시 내 곁으로 돌아갔으면 해 
 네가 내게로 오는 이 시간이 
 너무나 길어 너무 들어 
 난 다시 네게 다가가고 싶은데 
 이제 그만 너를 잡고 싶은데 
 나는 왜 널 떠나가야 하는지 
 날 버리지는 않길 바랄 뿐 
 
 차라리 니가 미워져 
 제발 떠나지마 나를 떠나가지마 
 지금 이 모든 걸 내 마음 속 너에게 말하고 싶어 
 널 두고 떠날 수 없다고 
 나는 너를 떠나야만 한다고 
 하지만 아직도 넌 날 떠나가고 있는 거니 
 내가 다 이해해줘 이런 나 때문에 
 너를 잊지 못했어 이런 날 용서해 
 나도 너를 잊을 수가 없잖아 
 너에겐 너무도 많은 걸 알고 있는데 
 이렇게 넌 나에게서 멀어져 가는걸 
 넌 다시 내 곁으로 돌아갔으면 해 
 네가 내게로 오는 이 시간이 
 너무나 길어 너무 들어 
 난 다시 네게 다가가고 싶은데 
 이제 그만 너를 잡고 싶은데 
 나는 왜 널 떠나가야 하는지 
 날 버리지는 않길 바랄 뿐
0.0
이건 누가 봐도 사랑일 텐데 
 난 너와의 얘기라면 전부 믿을 텐데 
 내가 먼저 만나지 말 것을 그랬어 
 그 말이 뭐가 중요한지를 모르겠어 
 이젠 나 혼자서 너를 보내야 해 
 네가 없으면 살아갈 수 없는데 
 내가 먼저 연락하지 마 
 우리 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 아침까지 
 
 이건 누구 봐도 사랑일 텐데 뭐 
 누굴 만나도 나는 이렇게 행복한데 
 왜 아무 말도 못 해 망설이기만 해 
 
 우린 헤어질 수 밖에 없어 
 
 모든 게 너와 처음 같아 
 
 우리 만난 걸 행운이라고 생각해 
 우린 더 많은 시간들을 함께 하고 있잖아 
 지금 나의 눈을 바라봐 지금 내 맘을 봐 
 
 다 해줄게 다 받아줄게 
 넌 그냥 그대로 있어주면 돼 
 모두 주고 싶어 모두 주고싶어 
 
 내가 잘 할게 다 해 줄게 
 난 정말 네가 원하는 걸 다 
 
 항상 널 보고 있는 나 
 너무 행복해서 눈물이 났어 
 
 오직 너 뿐이야 
 
 모든 게 너와 처음 같아 
 우리 만난 걸 행운이라고 생각해 
 우린 더 많은 시간들을 함께 하고 있잖아 
 지금 나의 눈을 바라봐 지금 내 맘을 봐 
 
 다 해줄게 다 받아줄게 
 넌 그냥 그대로 있어주면 돼 
 모두 주고 싶어 모두 주고싶어 
 
 내가 잘 할게 다 해 줄게 
 난 정말 네가 원하는 걸 다
0.0
이건 누가 봐도 사랑일 텐데 아침까지 
 
 이건 누구 봐도 사랑일 텐데 뭐 
 누굴 만나도 나는 이렇게 행복한데 
 왜 아무 말도 못 해 망설이기만 해 
 
 우린 헤어질 수 밖에 없어 
 
 모든 게 너와 처음 같아 
 
 우리 만난 걸 행운이라고 생각해 
 우린 더 많은 시간들을 함께 하고 있잖아 
 지금 나의 눈을 바라봐 지금 내 맘을 봐 
 
 다 해줄게 다 받아줄게 
 넌 그냥 그대로 있어주면 돼 
 모두 주고 싶어 모두 주고싶어 
 
 내가 잘 할게 다 해 줄게 
 난 정말 네가 원하는 걸 다 
 
 항상 널 보고 있는 나 
 너무 행복해서 눈물이 났어 
 
 오직 너 뿐이야 
 
 모든 게 너와 처음 같아 
 우리 만난 걸 행운이라고 생각해 
 우

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


['topic2']
[('topic2', 1)]
['topic2']
[('topic2', 1)]
tensor([[42000, 42004, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 네게 전할 말이 
 난 너만 보면 기분이 참 좋대 
 너도 나만큼 설레길 바래 
 내 맘속에 네 표정은 
 이미 나를 향해 있어 
 네가 보고싶어 질 때 마다 
 내 시간은 어느새 멈추고 
 너에게 가고 있는 거 같아 
 너를 좋아 하고 싶은걸 baby 
 ill always love you forever with you 
 이건 널 만난 후로부터 
 나의 전부가 돼버린 걸 yeah 
 매일 난 기도해 
 네가 오길 나 무엇을 하든지 
 너는 이제 내꺼야 baby 
 i just wanna know 
 너를 좋아하고 있다고 
 너도 나만큼 날 원한다고 
 너도 나만큼 내 맘과 같았으면 해 
 내가 보고싶어 질 때 마다 
 내 시간은 어느새 멈추고 
 너에게 가고 있는 거 같아 
 너를 좋아 하고 싶은걸 baby 
 ill always love you forever with you 
 이건 널 만난 후로부터 
 나의 전부가 돼버린 걸 yeah 
 매일 난 기도해 
 네가 오길 나 무엇을 하든지 
 너는 이제 내꺼야 baby 
 dont go away from me baby 
 always still loving you 
 i just wanna know 
 너를 좋아하고 있다고 
 너는 이제 내꺼야 baby 
 i can tell you youre my girl 
 너는 나만 보면 좋은가 봐
0.3655030800821355
이건 누가 봐도 사랑일 텐데 네게 전할 말이 
 난 너만 보면 기분이 참 좋대 
 너도 나만큼 설레길 바래 
 내 맘속에 네 표정은 
 이미 나를 향해 있어 
 네가 보고싶어 질 때 마다 
 내 시간은 어느새 멈추고 
 너에게 가고 있는 거 같아 
 너를 좋아 하고 싶은걸 baby 
 ill always love you forever with you 
 이건 널 만난 후로부터 
 나의 전부가 돼버린 걸 yeah 
 매일 난 기도해 
 네가 오길 나 무엇을 하든지 
 너는 이제 내꺼야 baby 
 i just wa

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


['topic2']
[('topic2', 1)]
['topic2']
[('topic2', 1)]
tensor([[42000, 42004, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 이제는 떠나줄래 
 너는 지금 이런 나의 모습이 
 처음이지 정말 이래 
 나는 혼자인 게 익숙지 않아 
 내가 너에게 어떤 사랑을 원하고 있는지 
 잘 생각해봐 내게 말을 해봐 
 니가 정말로 원하는 걸 말해봐 
 너와 함께 가고 싶어 이 길을 
 함께 걷고 싶어 모든 게 꿈만 같아 
 사랑도 너무 달콤해 
 너는 나에게 너무 부족한 사람이니까 
 이런 마음 가질 자격 있는 나인데 
 그냥 나와준다면 행복해 
 나는 너를 너무 사랑하지 
 매일 너의 생각만 하다가 
 이제는 정말 난 못하겠어 
 너와 함께 걷고 싶어 이 길을 
 함께 걷고 싶어 모든 게 꿈만 같아 
 사랑도 너무 달콤해 
 너는 나에게 너무 부족한 사람이니까 
 이런 마음 가질 자격 있는 나잖아 
 다신 생각하지 않을래 이제 
 너를 사랑하기 때문에 
 행복할 수 있도록 더 사랑할게 
 항상 이렇게 사랑할지 몰라 
 너의 두 눈에 흐르는 눈물이 
 난 정말 난 싫어 
 너는 나에게 너무 부족한 사람이니까 
 이런 마음 가질 자격 있는 나인데 
 그냥 나와준다면 행복해
0.0
이건 누가 봐도 사랑일 텐데 이제는 떠나줄래 
 너는 지금 이런 나의 모습이 
 처음이지 정말 이래 
 나는 혼자인 게 익숙지 않아 
 내가 너에게 어떤 사랑을 원하고 있는지 
 잘 생각해봐 내게 말을 해봐 
 니가 정말로 원하는 걸 말해봐 
 너와 함께 가고 싶어 이 길을 
 함께 걷고 싶어 모든 게 꿈만 같아 
 사랑도 너무 달콤해 
 너는 나에게 너무 부족한 사람이니까 
 이런 마음 가질 자격 있는 나인데 
 그냥 나와준다면 행복해 
 나는 너를 너무 사랑하지 
 매일 너의 생각만 하다가 
 이제는 정말 난 못하겠어 
 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


['topic2', 'topic2']
[('topic2', 2)]
['topic2', 'topic2']
[('topic2', 2)]
tensor([[42000, 42004, 33721, 15830, 38054,  8013,     3]], device='cuda:0')
사랑은 가슴아프다 예의 욕합 
 사랑노래도 모두 다 노래를 해줘 
 랄랄랄라 랄라라 라랄라라 
 랄라랄라 랄라라 라랄라라 
 내가 내가 내가 먼저 손을 내밀어 봐 
 내가 내가 내가 먼저 다가갈게 
 나를 나를 나를 불러봐 
 나는 나는 나는 너를 사랑해 
 사랑해 사랑해 너를 사랑해 
 내가 내가 내가 먼저 손을 내밀어 봐 
 내가 내가 내가 먼저 다가갈게 
 내가 내가 내가 내가 먼저 다가갈게 
 내가 내가 내가 내가 먼저 다가갈게 
 나를 내가 내가 사랑해 
 내가 내가 내가 내가 먼저 
 내가 내가 내가 먼저 다가갈게 
 내가 내가 내가 내가 먼저 다가갈게 
 랄랄라 랄라라 라랄라라 
 랄라랄라 랄라라 라랄라라 
 내가 내가 내가 먼저 손을 내밀어 봐 
 내가 내가 내가 먼저 다가갈게 
 나를 내가 내가 니가라고 생각할게
0.0
사랑은 가슴아프다 예의 욕합 
 사랑노래도 모두 다 노래를 해줘 
 랄랄랄라 랄라라 라랄라라 
 랄라랄라 랄라라 라랄라라 
 내가 내가 내가 먼저 손을 내밀어 봐 
 내가 내가 내가 먼저 다가갈게 
 나를 나를 나를 불러봐 
 나는 나는 나는 너를 사랑해 
 사랑해 사랑해 너를 사랑해 
 내가 내가 내가 먼저 손을 내밀어 봐 
 내가 내가 내가 먼저 다가갈게 
 내가 내가 내가 내가 먼저 다가갈게 
 내가 내가 내가 내가 먼저 다가갈게 
 나를 내가 내가 사랑해 
 내가 내가 내가 내가 먼저 
 내가 내가 내가 먼저 다가갈게 
 내가 내가 내가 내가 먼저 다가갈게 
 랄랄라 랄라라 라랄라라 
 랄라랄라 랄라라 라랄라라 
 내가 내가 내가 먼저 손을 내밀어 봐 
 내가 내가 내가 먼저 다가갈게 
 나를 내가 내가 니가라고 생각할게
INFO:     211.178.2

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 왜 이래 
 우린 정말 잘 맞는데 
 우린 이제 끝나버렸잖아 
 난 니가 뭘 어떡해도 
 잘 지내라 해줘 
 근데 잘 안돼 그게 안돼 yeah 
 이건 내가 봐도 난 너만 바라봐 
 너는 나만 바라봐 
 내가 정말 
 니가 정말 내 사람인 것 같대 uh uh uh 
 내가 정말 
 니가 정말로 내 사람이면 uh uh uh 
 니가 정말 
 나밖에 없을 것만 같대 uh uh uh uh 
 나는 결국 
 너밖에 없으니까 
 너도 알겠지 난 니가 전부니까 
 나도 알 거야 난 니가 전부니까 
 ooh ooh aoh ooh aoh ooh aoh 
 ooh ooh aoh aoh aoh aoh 
 ooh ooh aoh aoh aoh aoh 
 ooh ooh aoh aoh aoh 
 우린 정말 잘 맞는데 
 우린 이제 끝나버렸잖아 
 왜 이제 온거야 왜 
 날 사랑하게 만드니 
 왜 이게 너인데 
 널 왜 밀어내니 
 너무 들어 
 난 나쁜 남자야 넌 좋은 남자야 
 니가 정말 사랑인 것 같대 uh uh uh 
 니가 정말 
 나밖에 없을 것만 같대 uh uh uh uh 
 나는 결국 
 너밖에 없으니까 
 너도 알겠지 난 니가 전부니까 
 나도 알 거야 난 니가 전부니까 
 ooh ooh aoh ooh aoh ooh 
 ooh ooh aoh aoh aoh 
 oo
0.31938325991189426
이건 누가 봐도 사랑일 텐데 왜 이래 
 우린 정말 잘 맞는데 
 우린 이제 끝나버렸잖아 
 난 니가 뭘 어떡해도 
 잘 지내라 해줘 
 근데 잘 안돼 그게 안돼 yeah 
 이건 내가 봐도 난 너만 바라봐 
 너는 나만 바라봐 
 내가 정말 
 니가 정말 내 사람인 것 같대 uh uh uh 
 내가 정말 
 니가 정말로 내 사람이면 uh uh uh 
 니가 정말 
 나밖에 없을 것만 같대 uh uh uh uh 
 나는 결국 
 너밖에 없으니까 
 너도 알겠지 난 니가 전부니까 
 나도 알 거야 난 니가 전부니까 
 ooh ooh aoh ooh a

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 아주 잘난 건 누가 봐도 
 모두 내가 꿈꿨던 사람인데 
 이렇게 모든 것이 바뀌면 어떡하라고 
 너만 바라보고 있어 난 
 i want to be with you only love 
 내 전부를 주고 싶어 
 i need love 너와 함께 하고 싶은데 
 i need love 너만 사랑하겠어 
 baby love in my life 
 이렇게 모두 다 너 하나야 
 왜 너야 나밖에 모르는데 
 oh dont let me down 
 넌 나만 따라와 
 언제나 너에게 나는 
 oh bebe baby baby 
 난 난 너의 필요해 
 oh baby baby 
 내가 다가갈 거야 
 oh woah oh wooah 
 you are your eyes on my mind 
 네게 빠졌어 
 i can already know 
 니가 얼마나 내게 큰지 난 알게 됐어 
 니가 너무 좋아 너만 보이잖아 
 너무 좋은 걸 
 우리 같이 손잡고 걸어볼까 우리 
 baby l o v e 너를 위해 
 너는 나에게 빠져버린걸 
 no matter what will it say 
 yeah my lady my first love 
 널 바라 봐 
 everyway 난 너만 있으면 돼 
 oh baby baby 
 baby one more time 
 you are the one for me 
 내게 와 
 yes we are the girl of the future 
 니 모든 게 다 
 i gotta leave 
 널 바라봐 ay so truly boy 
 넌 날 웃게 해 날 꿈꾸게 해 
 what can i say leave me ay you baby
0.5502555366269165
이건 누가 봐도 사랑일 텐데 아주 잘난 건 누가 봐도 
 모두 내가 꿈꿨던 사람인데 
 이렇게 모든 것이 바뀌면 어떡하라고 
 너만 바라보고 있어 난 
 i want to be with you only love 
 내 전부를 주고 싶어 
 i need love 너와

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 27206,  8311,     3]],
       device='cuda:0')
이건 누가 봐도 사랑이야귓가 
 이거보고 설마 
 이거하고 무슨소리야 
 이 좋은 세상을 위해 만든 노래 
 이 좋은 세상을 위해 만든 노래 
 이거하고 뭐해 에라 모르겠다 
 에라 모르겠다 
 사랑하자 사랑하자 
 우린 정말 너무나도 너무나도 
 많이도 서로에게 너무나 
 많이도 지치기도 너무나 든 일이 많이도 
 서로 손을 잡고 얘기할 수 있는 조그만 
 작은 희망이 되어줘 
 사랑이라는 말조차 서로가 모르게 
 그 어떤 얘기도 아무런 가 하지는 말어 
 나는 오직 그대만 믿을래요 
 내가 그댈 언제까지나 믿어요 
 이 좋은 세상을 위해 만든 노래 
 이 좋은 세상을 위해 만든 노래 
 
 저 멀리 하늘을 날아요 
 저 높이 하늘 높이 
 저 멀리 바다 건너서 
 오 그대가 있어 난 너무 기분 좋아요 
 나의 이 큰 사랑 내게 줘서 고마워요 
 
 난 이 넓은 세상에 
 저 빛이 될래요 
 저 멀리 바다 건너서 
 오 그대가 있어 난 너무 기분 좋아요 
 나의 이 큰 사랑 내게 줘서 고마워요
0.0
이건 누가 봐도 사랑이야귓가 
 이거보고 설마 
 이거하고 무슨소리야 
 이 좋은 세상을 위해 만든 노래 
 이 좋은 세상을 위해 만든 노래 
 이거하고 뭐해 에라 모르겠다 
 에라 모르겠다 
 사랑하자 사랑하자 
 우린 정말 너무나도 너무나도 
 많이도 서로에게 너무나 
 많이도 지치기도 너무나 든 일이 많이도 
 서로 손을 잡고 얘기할 수 있는 조그만 
 작은 희망이 되어줘 
 사랑이라는 말조차 서로가 모르게 
 그 어떤 얘기도 아무런 가 하지는 말어 
 나는 오직 그대만 믿을래요 
 내가 그댈 언제까지나 믿어요 
 이 좋은 세상을 위해 만든 노래 
 이 좋은 세상을 위해 만든 노래 
 
 저 멀리 하늘을 날아요 
 저 높이 하늘 높이 
 저 멀리 바다 건너서 
 오 그대가 있

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 16810,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일텐데 
 이럴려고 그랬어 
 내가 너에게 잘못한것이 사실이라면 
 어떻게 해야만 했어 
 난 사랑을 잘 몰라서 
 니맘도 몰라주는 
 그저 바보같이 
 그저 착한 여자로 만든거야 
 나도 널 사랑하긴 많이 부족해 
 내 맘 받아줄 수 있겠니 
 이런 날 용서해 
 이젠 다시 울지 않겠어 
 제발 나에게서 멀어져 
 난 너없인 안될것 같아 
 
 차라리 사랑한단 말보다 
 니곁에 있기만 했던게 
 이런 말 후회는 없어 
 이제는 내 맘 알아주겠니 
 이제 그만 헤어져 
 제발 내 맘을 좀 더 열어줘 
 다시 너를 사랑하고 싶어 
 너와 함께 할 수 있을때까지 
 이제는 너를 보내줄께 
 내 모든 기억들 
 전부 너란걸 알잖아 
 그렇게 너를 사랑하는 거야 
 
 정말 미안해 
 넌 아직 모르니 
 정말 날 떠난거니 
 너의 집앞을 내가 가야만 하니까 
 
 이런날 용서해 
 이젠 다시 울지 않겠어 
 제발 나에게서 멀어져 
 난 너없인 안될것 같아
0.0
이건 누가 봐도 사랑일텐데 
 이럴려고 그랬어 
 내가 너에게 잘못한것이 사실이라면 
 어떻게 해야만 했어 
 난 사랑을 잘 몰라서 
 니맘도 몰라주는 
 그저 바보같이 
 그저 착한 여자로 만든거야 
 나도 널 사랑하긴 많이 부족해 
 내 맘 받아줄 수 있겠니 
 이런 날 용서해 
 이젠 다시 울지 않겠어 
 제발 나에게서 멀어져 
 난 너없인 안될것 같아 
 
 차라리 사랑한단 말보다 
 니곁에 있기만 했던게 
 이런 말 후회는 없어 
 이제는 내 맘 알아주겠니 
 이제 그만 헤어져 
 제발 내 맘을 좀 더 열어줘 
 다시 너를 사랑하고 싶어 
 너와 함께 할 수 있을때까지 
 이제는 너를 보내줄께 
 내 모든 기억들 
 전부 너란걸 알잖아 
 그렇게 너를 사랑하는 거야 
 
 정말 미안해 


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')


Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


이건 누가 봐도 사랑일 텐데 지금 이 시간 
 널 찾아갈 거라고 생각해 
 너를 위한 내 마음을 말해 볼 테니 
 지금 이 순간 널 만나러 가 
 우린 다른 곳을 보지 않아 
 이렇게 너를 기다리는데 
 내가 뭘 원했는지도 너는 몰라 
 하지만 난 너에게 네게 말할 게 yeah 
 너는 날 믿으면 돼 
 내 마음을 받아 줘 uh baby 
 그댈 사랑해요 
 우리 함께해요 
 이젠 나의 손 놓지 말아요 baby 
 내가 더 잘할게요 oh baby 
 넌 나만 믿고 따라와 
 이제 우리만 해요 my love oh girl 
 널 사랑하는데 난 난 자신 있는데 
 oh 너와 난 특별한 존재야 너와 난 
 you know the world is over without yeah 
 너만 보는 나의 마음 im gonna be alright 
 i miss you all the time i think about yeah 
 너도 내 사랑을 알아 
 너의 곁에 언제나 머물고 싶은 나 인걸 
 날 바라봐 줘요 내게로 와요 baby 
 나는 네게 모든 걸 주고 싶어 
 널 사랑하는데 난 난 자신 있는데 
 oh 너와 난 특별한 존재야 너와 난 
 you know the world is over without yeah 
 너만 보는 나의 마음 im gonna be alright 
 i miss you all the time i think about yeah 
 네가 더 
 내게서 멀어지지만 yeah 
 오직 난 영원히 
 우린 서로만 보며 웃을 거야 forever 
 oh 넌 그냥 나에게 
 더는 아무런 잘못이 없어 
 나조차 네 옆에서 
 너를 지켜 줄 수 밖에 없잖아 
 너의 작은 배려와 너의 소중한 눈빛에
0.36317567567567566
이건 누가 봐도 사랑일 텐데 지금 이 시간 
 널 찾아갈 거라고 생각해 
 너를 위한 내 마음을 말해 볼 테니 
 지금 이 순간 널 만나러 가 
 우린 다른 곳을 보지 않아 
 이렇게 너를 기다리는데 
 내가 뭘 원했는지도 너는 몰라 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 
 이건 누가 봐도 사랑일 텐데 
 이젠 내가 지켜줄 게 
 내 곁에 머물러줘 나를 사랑해줘 
 너는 나를 사랑해 줄 수 없어 
 너는 이제 그런 사람 아냐 
 나는 네게 전부를 준 거야 
 내게 말했었잖아 약속했었잖아 
 이제 와서 이런 바보들 또 뭔데 
 난 너희들과 지치고 있는데 
 너를 향한 그 마음만 변치 않고 
 나를 안아줘 
 이 많은 감정을 네게 던져 
 나에게 모두 줘 
 난 네가 가진 유일한 행복인 걸 
 내가 네 손 꼭 잡을게 
 이제는 아무 걱정하지 마 
 우리만의 세상에서 
 서로 같이 만들어갈래 
 이젠 나를 봐줘 
 항상 너와 함께 했던 날 동안 
 참았던 나의 맘이 널 사랑해 
 니가 정말 원한 세상에 나를 살게 해줬어 
 그 마음 다 받아준 날 위해 
 내가 노력할게 너를 
 우리 사랑을 영원토록 기억할게 
 나를 사랑해 줘
0.0
이건 누가 봐도 사랑일 텐데 
 이건 누가 봐도 사랑일 텐데 
 이젠 내가 지켜줄 게 
 내 곁에 머물러줘 나를 사랑해줘 
 너는 나를 사랑해 줄 수 없어 
 너는 이제 그런 사람 아냐 
 나는 네게 전부를 준 거야 
 내게 말했었잖아 약속했었잖아 
 이제 와서 이런 바보들 또 뭔데 
 난 너희들과 지치고 있는데 
 너를 향한 그 마음만 변치 않고 
 나를 안아줘 
 이 많은 감정을 네게 던져 
 나에게 모두 줘 
 난 네가 가진 유일한 행복인 걸 
 내가 네 손 꼭 잡을게 
 이제는 아무 걱정하지 마 
 우리만의 세상에서 
 서로 같이 만들어갈래 
 이젠 나를 봐줘 
 항상 너와 함께 했던 날 동안 
 참았던 나의 맘이 널 사랑해 
 니가 정말 원한 세상에 나를 살게 해줬어 
 그 마음 다 받아준 날 위해 
 내가 노력할게 너를 
 우리 사랑을 영원토록 기억할게 
 나를 사랑해 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 
 이렇게까지 사랑을 받을 줄 몰랐어요 
 이런 감정 처음인데 
 
 우린 정말 어떤 이별을 받았나요 
 처음 본 순간 느꼈어요 
 나의 이런 마음을 알아주면 안 되겠니 
 
 이 여자 참 아름다워라 
 이 남자 참 향기로워라 
 이 남자 참 못 헤웠네 
 내 앞에서 날 보고 웃고 웃고 
 내 앞에 있는 그댄 정말 아름다워요 
 
 한순간도 난 너를 잊은 적이 없어 
 난 그냥 사랑이고파 
 내겐 그 사랑보다 이 세상에서 
 널 더 사랑해줄 한 사람 
 
 이 여자 참 아름다워라 
 이 남자 참 향기로워라 
 이 남자 참 못 헤웠네 
 내 앞에서 날 보고 웃고 웃고 
 내 앞에 있는 그댄 정말 아름다워요 
 
 단 한마디도 따뜻하게 건네주지를 못했어 
 단 한 번도 안아주지도 못했어 
 정말 미안해 이 바보야 
 왜 이렇게 나를 아프게만 해 
 왜 나만 또 아프게 해 
 
 이 여자 참 아름다워라 
 이 남자 참 향기로워라 
 이 남자 참 못 헤웠네 
 내 앞에서 날 보고 웃고 웃고 
 내 앞에 있는 그댄 정말 아름다워요 
 이 세상 가장 행복한 여자야 
 이 예쁜 걸요
0.0
이건 누가 봐도 사랑일 텐데 
 이렇게까지 사랑을 받을 줄 몰랐어요 
 이런 감정 처음인데 
 
 우린 정말 어떤 이별을 받았나요 
 처음 본 순간 느꼈어요 
 나의 이런 마음을 알아주면 안 되겠니 
 
 이 여자 참 아름다워라 
 이 남자 참 향기로워라 
 이 남자 참 못 헤웠네 
 내 앞에서 날 보고 웃고 웃고 
 내 앞에 있는 그댄 정말 아름다워요 
 
 한순간도 난 너를 잊은 적이 없어 
 난 그냥 사랑이고파 
 내겐 그 사랑보다 이 세상에서 
 널 더 사랑해줄 한 사람 
 
 이 여자 참 아름다워라 
 이 남자 참 향기로워라 
 이 남자 참 못 헤웠네 
 

Setting `pad_token_id` to `eos_token_id`:3 for open-end generation.


[]
[]
[]
[]
tensor([[42000, 42014, 14712, 16522, 16657, 14366,  8066, 20326,     3]],
       device='cuda:0')
이건 누가 봐도 사랑일 텐데 
 
 
 난 너 같은 사람 사랑해 줄 사람 찾아 헤맸어 
 네가 보는 지금의 내가 
 불행할지는 모르겠어 
 
 
 
 넌 이런 바보같은 사람 
 만나봤음 좋겠지만 
 그렇게도 무참히 버려진 
 너의 사랑이 나는 너무 외로워 
 
 다른 여잘 사귀고 있는 나를 지워줘 
 내 아픈 기억 지워줘 
 한여자로 사랑으로 울릴 여자라면 
 나보다 못한 사람을 사랑해줘 
 그 누구도 너처럼 행복할 수는 없어 
 
 
 
 
 이런 저런 핑계 대지 마 
 차라리 니 곁에 있을 때 
 후회할지는 몰라도 
 넌 나와 같겠지 
 
 
 
 
 
 
 
 
 
 
 
 난 이런 바보같은 사람 
 만나 봤음 좋겠지만 
 그렇게도 무참히 버려진 
 너의 사랑이 나는 너무 외로워 
 다른 여잘 사귀고 있는 나를 지워 줘 
 내 아픈기억 지워줘 
 한여자로 사랑으로 울릴 여자라면 
 나보다 못한 사람을 사랑해 줘 
 그 누구도 너처럼 행복할 수는 없어 
 
 
 
 나같이 나쁜 남자를 만나 
 내가 잘 못 된 여자라고 원망해 
 그 어떤 것도 필요 없는 걸 
 나도 잘 알아 알아 
 널 내 여자로 만들고 싶진 않지만 
 사랑할 수 밖에 없어 정말
0.0
이건 누가 봐도 사랑일 텐데 
 
 
 난 너 같은 사람 사랑해 줄 사람 찾아 헤맸어 
 네가 보는 지금의 내가 
 불행할지는 모르겠어 
 
 
 
 넌 이런 바보같은 사람 
 만나봤음 좋겠지만 
 그렇게도 무참히 버려진 
 너의 사랑이 나는 너무 외로워 
 
 다른 여잘 사귀고 있는 나를 지워줘 
 내 아픈 기억 지워줘 
 한여자로 사랑으로 울릴 여자라면 
 나보다 못한 사람을 사랑해줘 
 그 누구도 너처럼 행복할 수는 없어 
 
 
 
 
 이런 저런 핑계 대지 마 
 차라리 니 곁에 있을 때 
 후회할지는 몰

INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [81]


In [ ]:
#    1 # app.mount("/public", StaticFiles(directory=os.path.join(BASE_DIR, "static/public")), name="static")
# ----> 2 BASE_
# width="600px" height="500px" 